(deftheme alect-dark
  "Created 2015-08-26.")

(custom-theme-set-variables
 'alect-dark
 '(ansi-color-names-vector ["#3f3f3f" "#ea3838" "#7fb07f" "#fe8b04" "#62b6ea" "#e353b9" "#1fb3b3" "#d5d2be"])
 '(gnus-mode-line-image-cache (quote (image :type xpm :ascent center :data "/* XPM */
static char *gnus-pointer[] = {
/* width height num_colors chars_per_pixel */
\"    18    13        2            1\",
/* colors */
\". c #1fb3b3\",
\"# c None s None\",
/* pixels */
\"##################\",
\"######..##..######\",
\"#####........#####\",
\"#.##.##..##...####\",
\"#...####.###...##.\",
\"#..###.######.....\",
\"#####.########...#\",
\"###########.######\",
\"####.###.#..######\",
\"######..###.######\",
\"###....####.######\",
\"###..######.######\",
\"###########.######\" };")))
 '(gnus-logo-colors (quote ("#528d8d" "#c0c0c0")))
 '(diary-entry-marker (quote font-lock-variable-name-face)))

(custom-theme-set-faces
 'alect-dark
 '(cursor ((((type graphic)) :background "#ffec8b")))
 '(button ((((type graphic)) :inherit link :underline (:color "#d5d2be"))))
 '(link ((((type graphic)) :foreground "#94bff3" :underline t)))
 '(link-visited ((((type graphic)) :foreground "#3390dc" :underline t)))
 '(match ((((type graphic)) :background "#3cb370" :foreground "#e9e9e9")))
 '(escape-glyph ((((type graphic)) :foreground "#fe8b04" :weight bold)))
 '(fringe ((((type graphic)) :foreground "#9f9f9f" :background "#222222")))
 '(header-line ((((type graphic)) :foreground "#f6f0e1" :height 1.13 :box (:line-width 1 :color "#f6f0e1" :style nil))))
 '(highlight ((((type graphic)) :foreground "#000000" :background "#e9e9e9")))
 '(shadow ((((type graphic)) :foreground "#9f9f9f")))
 '(success ((((type graphic)) :foreground "#7fb07f" :weight bold)))
 '(error ((((type graphic)) :foreground "#ea3838" :weight bold)))
 '(warning ((((type graphic)) :foreground "#e8e815")))
 '(region ((((type graphic)) :background "#6f6f6f")))
 '(menu ((((type graphic)) :foreground "#f6f0e1" :background "#222222" :height 1.13)))
 '(tool-bar ((((type graphic)) :inherit mode-line)))
 '(scroll-bar ((((type graphic)) :background "#6f6f6f")))
 '(tooltip ((((type graphic)) :inherit variable-pitch :foreground "#0c8782" :background "#222222")))
 '(minibuffer-prompt ((((type graphic)) :inherit alect-prompt)))
 '(secondary-selection ((((type graphic)) :background "#5f5f5f")))
 '(trailing-whitespace ((((type graphic)) :background "#ea3838")))
 '(vertical-border ((((type graphic)) :foreground "#d5d2be")))
 '(window-divider ((((type graphic)) :foreground "#099709")))
 '(window-divider-first-pixel ((((type graphic)) :foreground "#3cb370")))
 '(window-divider-last-pixel ((((type graphic)) :inherit window-divider-first-pixel)))
 '(alect-prompt ((((type graphic)) :foreground "#dc8cc3" :weight bold)))
 '(alect-time ((((type graphic)) :foreground "#8cf1f1")))
 '(alect-author ((((type graphic)) :foreground "#dc8cc3")))
 '(alect-key ((((type graphic)) :foreground "#fa6a6e" :weight bold)))
 '(alect-selected-item ((((type graphic)) :background "#4f4f4f" :box (:line-width -1 :color "#d5d2be" :style nil))))
 '(alect-color-level-1 ((((type graphic)) :foreground "#00aff5")))
 '(alect-color-level-2 ((((type graphic)) :foreground "#7fb07f")))
 '(alect-color-level-3 ((((type graphic)) :foreground "#db4334")))
 '(alect-color-level-4 ((((type graphic)) :foreground "#abab3a")))
 '(alect-color-level-5 ((((type graphic)) :foreground "#528d8d")))
 '(alect-color-level-6 ((((type graphic)) :foreground "#94bff3")))
 '(alect-color-level-7 ((((type graphic)) :foreground "#dc8cc3")))
 '(alect-color-level-8 ((((type graphic)) :foreground "#fe8b04")))
 '(alect-color-level-9 ((((type graphic)) :foreground "#32cd32")))
 '(alect-color-level-10 ((((type graphic)) :foreground "#fa6a6e")))
 '(alect-color-level-11 ((((type graphic)) :foreground "#8cf1f1")))
 '(alect-color-level-12 ((((type graphic)) :foreground "#be59d8")))
 '(alect-title ((((type graphic)) :foreground "#099709" :weight bold :height 1.13)))
 '(alect-title-1 ((((type graphic)) :inherit alect-color-level-1 :weight bold :height 1.13)))
 '(alect-title-2 ((((type graphic)) :inherit alect-color-level-2 :weight bold :height 1.13)))
 '(alect-title-3 ((((type graphic)) :inherit alect-color-level-3 :weight bold :height 1.13)))
 '(alect-title-4 ((((type graphic)) :inherit alect-color-level-4 :weight bold :height 1.13)))
 '(alect-title-5 ((((type graphic)) :inherit alect-color-level-5 :weight bold :height 1.13)))
 '(alect-title-6 ((((type graphic)) :inherit alect-color-level-6 :weight bold :height 1.13)))
 '(alect-title-7 ((((type graphic)) :inherit alect-color-level-7 :weight bold :height 1.13)))
 '(alect-title-8 ((((type graphic)) :inherit alect-color-level-8 :weight bold :height 1.13)))
 '(alect-button ((((type graphic)) :foreground "#f6f0e1" :background "#6f6f6f" :box (:line-width 2 :style released-button))))
 '(alect-button-pressed ((((type graphic)) :inherit alect-button :box (:line-width 2 :style pressed-button))))
 '(alect-button-mouse ((((type graphic)) :inherit highlight :box (:line-width 2 :style released-button))))
 '(alect-tab-default ((((type graphic)) :height 0.9 :box nil)))
 '(alect-tab-unselected ((((type graphic)) :inherit alect-tab-default :foreground "#8c826d" :background "#4f4f4f" :box (:line-width 1 :style released-button))))
 '(alect-tab-selected ((((type graphic)) :inherit alect-tab-unselected :foreground "#f6f0e1" :background "#5f5f5f")))
 '(alect-tab-mouse ((((type graphic)) :inherit alect-tab-default :inherit mode-line-highlight)))
 '(apropos-keybinding ((((type graphic)) :inherit alect-key)))
 '(apropos-symbol ((((type graphic)) :foreground "#3cb370" :weight bold)))
 '(ac-candidate-face ((((type graphic)) :foreground "#000000" :background "#6f6f6f")))
 '(ac-selection-face ((((type graphic)) :foreground "#3f3f3f" :background "#d5d2be")))
 '(ac-completion-face ((((type graphic)) :foreground "#8c826d")))
 '(ac-candidate-mouse-face ((((type graphic)) :inherit highlight)))
 '(calendar-today ((((type graphic)) :box (:line-width -1 :color "#ea3838" :style nil))))
 '(diary ((((type graphic)) :foreground "#099709" :weight bold)))
 '(holiday ((((type graphic)) :background "#6f6f6f")))
 '(change-log-date ((((type graphic)) :inherit alect-time)))
 '(change-log-name ((((type graphic)) :inherit alect-author)))
 '(change-log-email ((((type graphic)) :foreground "#fa6a6e")))
 '(change-log-file ((((type graphic)) :foreground "#32cd32")))
 '(change-log-list ((((type graphic)) :inherit font-lock-function-name-face)))
 '(change-log-conditionals ((((type graphic)) :inherit font-lock-variable-name-face)))
 '(change-log-function ((((type graphic)) :foreground "#fe8b04")))
 '(change-log-acknowledgment ((((type graphic)) :inherit font-lock-keyword-face)))
 '(comint-highlight-prompt ((((type graphic)) :inherit alect-prompt)))
 '(comint-highlight-input ((((type graphic)) :weight bold)))
 '(company-tooltip ((((type graphic)) :foreground "#d0bf8f" :background "#5f5f5f")))
 '(company-tooltip-selection ((((type graphic)) :foreground "#d0bf8f" :background "#222222")))
 '(company-tooltip-mouse ((((type graphic)) :inherit highlight)))
 '(company-tooltip-annotation ((((type graphic)) :inherit company-tooltip :foreground "#62b6ea")))
 '(company-tooltip-common ((((type graphic)) :inherit company-tooltip :foreground "#d5d2be")))
 '(company-tooltip-common-selection ((((type graphic)) :inherit company-tooltip-selection :foreground "#d5d2be")))
 '(company-preview ((((type graphic)) :foreground "#d0bf8f")))
 '(company-preview-common ((((type graphic)) :inherit company-preview :underline t)))
 '(company-scrollbar-fg ((((type graphic)) :background "#505050")))
 '(company-scrollbar-bg ((((type graphic)) :background "#9f9f9f")))
 '(compilation-info ((((type graphic)) :foreground "#8ce096")))
 '(compilation-warning ((((type graphic)) :inherit warning)))
 '(compilation-error ((((type graphic)) :inherit error)))
 '(compilation-line-number ((((type graphic)) :foreground "#fe8b04")))
 '(compilation-column-number ((((type graphic)) :foreground "#abab3a")))
 '(compilation-mode-line-run ((((type graphic)) :foreground "#62b6ea")))
 '(compilation-mode-line-exit ((((type graphic)) :inherit success)))
 '(compilation-mode-line-fail ((((type graphic)) :inherit compilation-error)))
 '(custom-button ((((type graphic)) :inherit alect-button)))
 '(custom-button-pressed ((((type graphic)) :inherit alect-button-pressed)))
 '(custom-button-mouse ((((type graphic)) :inherit alect-button-mouse)))
 '(custom-button-unraised ((((type graphic)) :inherit alect-button :box nil)))
 '(custom-button-pressed-unraised ((((type graphic)) :inherit custom-button-unraised :underline t)))
 '(custom-documentation ((((type graphic)) :inherit font-lock-doc-face)))
 '(custom-comment ((((type graphic)) :foreground "#9f9f9f")))
 '(custom-state ((((type graphic)) :foreground "#3cb370")))
 '(custom-link ((((type graphic)) :inherit link)))
 '(custom-group-tag ((((type graphic)) :inherit alect-title-1)))
 '(custom-group-tag-1 ((((type graphic)) :inherit alect-title-2)))
 '(custom-group-subtitle ((((type graphic)) :inherit alect-title-3)))
 '(custom-face-tag ((((type graphic)) :foreground "#e81eda" :weight bold)))
 '(custom-variable-tag ((((type graphic)) :inherit font-lock-variable-name-face :weight bold)))
 '(custom-variable-button ((((type graphic)) :weight bold :underline t)))
 '(custom-visibility ((((type graphic)) :inherit link :height 0.8)))
 '(diff-context ((((type graphic)) :foreground "#d0bf8f")))
 '(diff-added ((((type graphic)) :foreground "#32cd32")))
 '(diff-changed ((((type graphic)) :foreground "#e8e815")))
 '(diff-removed ((((type graphic)) :foreground "#fa5151")))
 '(diff-indicator-added ((((type graphic)) :inherit diff-added)))
 '(diff-indicator-changed ((((type graphic)) :inherit diff-changed)))
 '(diff-indicator-removed ((((type graphic)) :inherit diff-removed)))
 '(diff-refine-added ((((type graphic)) :inherit diff-added :underline t)))
 '(diff-refine-changed ((((type graphic)) :inherit diff-changed :underline t)))
 '(diff-refine-removed ((((type graphic)) :inherit diff-removed :underline t)))
 '(diff-header ((((type graphic)) :foreground "#b2c3f8" :weight bold)))
 '(diff-hunk-header ((((type graphic)) :inherit diff-header :foreground "#099709")))
 '(diff-file-header ((((type graphic)) :inherit diff-header :foreground "#2fdbde")))
 '(diff-function ((((type graphic)) :inherit diff-header :foreground "#62b6ea")))
 '(diff-index ((((type graphic)) :inherit diff-header :foreground "#fa5151")))
 '(diff-nonexistent ((((type graphic)) :inherit diff-header :foreground "#9f9f9f")))
 '(dired-directory ((((type graphic)) :inherit font-lock-function-name-face)))
 '(dired-flagged ((((type graphic)) :foreground "#ea3838")))
 '(dired-header ((((type graphic)) :inherit alect-title)))
 '(dired-ignored ((((type graphic)) :foreground "#9f9f9f")))
 '(dired-mark ((((type graphic)) :foreground "#00aff5")))
 '(dired-marked ((((type graphic)) :inherit warning)))
 '(dired-perm-write ((((type graphic)) :foreground "#32cd32")))
 '(dired-symlink ((((type graphic)) :inherit font-lock-constant-face)))
 '(dired-warning ((((type graphic)) :inherit font-lock-warning-face :background "#222222")))
 '(ediff-even-diff-A ((((type graphic)) :background "#4f4f4f")))
 '(ediff-odd-diff-A ((((type graphic)) :background "#5f5f5f")))
 '(ediff-even-diff-B ((((type graphic)) :inherit ediff-even-diff-A)))
 '(ediff-odd-diff-B ((((type graphic)) :inherit ediff-odd-diff-A)))
 '(ediff-even-diff-C ((((type graphic)) :inherit ediff-even-diff-A)))
 '(ediff-odd-diff-C ((((type graphic)) :inherit ediff-odd-diff-A)))
 '(eldoc-highlight-function-argument ((((type graphic)) :foreground "#7fb07f" :weight bold)))
 '(epa-mark ((((type graphic)) :foreground "#00aff5")))
 '(epa-string ((((type graphic)) :foreground "#0c8782")))
 '(epa-validity-disabled ((((type graphic)) :foreground "#8c826d")))
 '(epa-validity-high ((((type graphic)) :foreground "#32cd32")))
 '(epa-validity-medium ((((type graphic)) :foreground "#e8e815")))
 '(epa-validity-low ((((type graphic)) :foreground "#fa5151")))
 '(flymake-errline ((((type graphic)) :foreground "#fa5151" :weight bold :underline t)))
 '(flymake-warnline ((((type graphic)) :foreground "#8c826d" :weight bold :underline t)))
 '(flyspell-duplicate ((((type graphic)) :foreground "#9f9f9f" :underline (:color "#f6f0e1"))))
 '(flyspell-incorrect ((((type graphic)) :inherit flyspell-duplicate :foreground "#db4334")))
 '(font-lock-builtin-face ((((type graphic)) :foreground "#dc8cc3")))
 '(font-lock-comment-face ((((type graphic)) :foreground "#3cb370")))
 '(font-lock-comment-delimiter-face ((((type graphic)) :inherit font-lock-comment-face)))
 '(font-lock-constant-face ((((type graphic)) :foreground "#2fdbde")))
 '(font-lock-doc-face ((((type graphic)) :foreground "#d0bf8f" :slant italic)))
 '(font-lock-function-name-face ((((type graphic)) :foreground "#94bff3")))
 '(font-lock-keyword-face ((((type graphic)) :foreground "#00aff5" :weight bold)))
 '(font-lock-negation-char-face ((((type graphic)) :foreground "#62b6ea")))
 '(font-lock-preprocessor-face ((((type graphic)) :foreground "#32cd32")))
 '(font-lock-string-face ((((type graphic)) :foreground "#fa6a6e")))
 '(font-lock-type-face ((((type graphic)) :foreground "#e81eda")))
 '(font-lock-variable-name-face ((((type graphic)) :foreground "#abab3a")))
 '(font-lock-warning-face ((((type graphic)) :foreground "#ea3838" :weight bold)))
 '(font-lock-regexp-grouping-backslash ((((type graphic)) :foreground "#c83029")))
 '(font-lock-regexp-grouping-construct ((((type graphic)) :foreground "#e8e815")))
 '(gnus-group-news-1-empty ((((type graphic)) :inherit alect-color-level-1)))
 '(gnus-group-news-2-empty ((((type graphic)) :inherit alect-color-level-2)))
 '(gnus-group-news-3-empty ((((type graphic)) :inherit alect-color-level-3)))
 '(gnus-group-news-4-empty ((((type graphic)) :inherit alect-color-level-4)))
 '(gnus-group-news-5-empty ((((type graphic)) :inherit alect-color-level-5)))
 '(gnus-group-news-6-empty ((((type graphic)) :inherit alect-color-level-6)))
 '(gnus-group-news-low-empty ((((type graphic)) :inherit alect-color-level-7)))
 '(gnus-group-news-1 ((((type graphic)) :inherit gnus-group-news-1-empty :weight bold)))
 '(gnus-group-news-2 ((((type graphic)) :inherit gnus-group-news-2-empty :weight bold)))
 '(gnus-group-news-3 ((((type graphic)) :inherit gnus-group-news-3-empty :weight bold)))
 '(gnus-group-news-4 ((((type graphic)) :inherit gnus-group-news-4-empty :weight bold)))
 '(gnus-group-news-5 ((((type graphic)) :inherit gnus-group-news-5-empty :weight bold)))
 '(gnus-group-news-6 ((((type graphic)) :inherit gnus-group-news-6-empty :weight bold)))
 '(gnus-group-news-low ((((type graphic)) :inherit gnus-group-news-low-empty :weight bold)))
 '(gnus-group-mail-1-empty ((((type graphic)) :inherit gnus-group-news-1-empty :slant italic)))
 '(gnus-group-mail-2-empty ((((type graphic)) :inherit gnus-group-news-2-empty :slant italic)))
 '(gnus-group-mail-3-empty ((((type graphic)) :inherit gnus-group-news-3-empty :slant italic)))
 '(gnus-group-mail-low-empty ((((type graphic)) :inherit gnus-group-news-low-empty :slant italic)))
 '(gnus-group-mail-1 ((((type graphic)) :inherit gnus-group-news-1 :slant italic)))
 '(gnus-group-mail-2 ((((type graphic)) :inherit gnus-group-news-2 :slant italic)))
 '(gnus-group-mail-3 ((((type graphic)) :inherit gnus-group-news-3 :slant italic)))
 '(gnus-group-mail-low ((((type graphic)) :inherit gnus-group-news-low :slant italic)))
 '(gnus-summary-cancelled ((((type graphic)) :background "#d0bf8f" :foreground "#222222")))
 '(gnus-summary-low-ancient ((((type graphic)) :foreground "#b2c3f8")))
 '(gnus-summary-low-read ((((type graphic)) :foreground "#8ce096")))
 '(gnus-summary-low-ticked ((((type graphic)) :foreground "#fa6a6e")))
 '(gnus-summary-low-unread ((((type graphic)) :foreground "#d0bf8f")))
 '(gnus-summary-normal-ancient ((((type graphic)) :foreground "#62b6ea")))
 '(gnus-summary-normal-read ((((type graphic)) :foreground "#7fb07f")))
 '(gnus-summary-normal-ticked ((((type graphic)) :foreground "#ea3838")))
 '(gnus-summary-normal-unread ((((type graphic)) :foreground "#d5d2be")))
 '(gnus-summary-high-ancient ((((type graphic)) :inherit gnus-summary-normal-ancient :weight bold)))
 '(gnus-summary-high-read ((((type graphic)) :inherit gnus-summary-normal-read :weight bold)))
 '(gnus-summary-high-ticked ((((type graphic)) :inherit gnus-summary-normal-ticked :weight bold)))
 '(gnus-summary-high-unread ((((type graphic)) :inherit gnus-summary-normal-unread :weight bold)))
 '(gnus-summary-selected ((((type graphic)) :inherit alect-selected-item)))
 '(helm-header ((((type graphic)) :inherit header-line)))
 '(helm-source-header ((((type graphic)) :inherit alect-title)))
 '(helm-separator ((((type graphic)) :foreground "#3390dc")))
 '(helm-M-x-key ((((type graphic)) :foreground "#fe8b04")))
 '(helm-selection ((((type graphic)) :background "#4f4f4f")))
 '(helm-selection-line ((((type graphic)) :background "#4f4f4f")))
 '(helm-visible-mark ((((type graphic)) :foreground "#e8e815")))
 '(helm-candidate-number ((((type graphic)) :background "#222222" :foreground "#8ce096")))
 '(helm-ff-file ((((type graphic)))))
 '(helm-ff-executable ((((type graphic)) :foreground "#32cd32")))
 '(helm-ff-directory ((((type graphic)) :inherit dired-directory)))
 '(helm-ff-symlink ((((type graphic)) :inherit dired-symlink)))
 '(helm-ff-invalid-symlink ((((type graphic)) :inherit dired-warning)))
 '(helm-ff-prefix ((((type graphic)) :background "#4f4f4f" :foreground "#db4334")))
 '(helm-buffer-directory ((((type graphic)) :inherit helm-ff-directory)))
 '(helm-buffer-saved-out ((((type graphic)) :background "#222222" :foreground "#ea3838")))
 '(helm-buffer-not-saved ((((type graphic)) :foreground "#fa6a6e")))
 '(helm-buffer-process ((((type graphic)) :foreground "#3cb370")))
 '(helm-buffer-size ((((type graphic)) :foreground "#1fb3b3")))
 '(helm-grep-file ((((type graphic)) :inherit compilation-info)))
 '(help-argument-name ((((type graphic)) :inherit font-lock-variable-name-face)))
 '(hl-line ((((type graphic)) :background "#4f4f4f")))
 '(hl-todo ((((type graphic)) :foreground "#ea3838" :weight bold)))
 '(info-title-1 ((((type graphic)) :inherit alect-color-level-1 :height 1.5 :weight bold)))
 '(info-title-2 ((((type graphic)) :inherit alect-color-level-2 :height 1.4 :weight bold)))
 '(info-title-3 ((((type graphic)) :inherit alect-color-level-3 :height 1.3 :weight bold)))
 '(info-title-4 ((((type graphic)) :inherit alect-color-level-4 :height 1.2 :weight bold)))
 '(info-menu-header ((((type graphic)) :inherit alect-color-level-5 :height 1.1 :weight bold)))
 '(info-node ((((type graphic)) :foreground "#db4334")))
 '(info-menu-star ((((type graphic)) :foreground "#ea3838")))
 '(Info-quoted ((((type graphic)) :foreground "#f6f0e1" :weight bold)))
 '(ido-first-match ((((type graphic)) :weight bold)))
 '(ido-only-match ((((type graphic)) :inherit ido-first-match :foreground "#62b6ea")))
 '(ido-subdir ((((type graphic)) :inherit dired-directory)))
 '(ido-virtual ((((type graphic)) :foreground "#fa6a6e")))
 '(isearch-fail ((((type graphic)) :foreground "#d5d2be" :background "#fa6a6e")))
 '(isearch ((((type graphic)) :foreground "#5f5f5f" :background "#f6f0e1")))
 '(lazy-highlight ((((type graphic)) :foreground "#222222" :background "#9f9f9f")))
 '(linum ((((type graphic)) :foreground "#8c826d")))
 '(git-commit-summary ((((type graphic)) :weight bold)))
 '(git-commit-comment-branch ((((type graphic)) :foreground "#62b6ea")))
 '(git-commit-comment-file ((((type graphic)) :inherit default)))
 '(git-commit-comment-heading ((((type graphic)) :inherit alect-title)))
 '(git-commit-comment-action ((((type graphic)) :foreground "#e5c900")))
 '(Man-overstrike ((((type graphic)) :foreground "#528d8d" :weight bold)))
 '(message-cited-text ((((type graphic)) :inherit font-lock-comment-face)))
 '(message-separator ((((type graphic)) :inherit font-lock-comment-face)))
 '(message-header-name ((((type graphic)) :foreground "#e5c900" :weight bold)))
 '(message-header-other ((((type graphic)) :foreground "#f0dfaf")))
 '(message-header-to ((((type graphic)) :foreground "#62b6ea")))
 '(message-header-cc ((((type graphic)) :foreground "#94bff3")))
 '(message-header-newsgroups ((((type graphic)) :foreground "#abab3a")))
 '(message-header-subject ((((type graphic)) :inherit alect-title)))
 '(message-header-xheader ((((type graphic)) :foreground "#32cd32")))
 '(message-mml ((((type graphic)) :foreground "#8cf1f1" :weight bold)))
 '(mode-line-buffer-id ((((type graphic)) :foreground "#94bff3" :weight bold)))
 '(mode-line ((((type graphic)) :foreground "#d5d2be" :background "#222222" :box (:line-width 2 :style released-button))))
 '(mode-line-inactive ((((type graphic)) :foreground "#8c826d" :background "#3f3f3f" :box (:line-width 2 :color "#222222" :style nil))))
 '(mode-line-highlight ((((type graphic)) :inherit highlight :box (:line-width 1 :style released-button))))
 '(org-agenda-date ((((type graphic)) :inherit alect-time)))
 '(org-agenda-date-today ((((type graphic)) :inherit alect-selected-item :foreground "#8cf1f1")))
 '(org-agenda-structure ((((type graphic)) :inherit alect-title)))
 '(org-archived ((((type graphic)) :foreground "#d5d2be" :weight bold)))
 '(org-block ((((type graphic)) :background "#4f4f4f")))
 '(org-block-begin-line ((((type graphic)) :inherit org-meta-line :background "#5f5f5f")))
 '(org-block-end-line ((((type graphic)) :inherit org-block-begin-line)))
 '(org-checkbox ((((type graphic)) :background "#222222" :foreground "#f0dfaf" :box (:line-width 1 :style pressed-button))))
 '(org-date ((((type graphic)) :inherit alect-time)))
 '(org-date-selected ((((type graphic)) :inherit alect-selected-item)))
 '(org-done ((((type graphic)) :foreground "#2fdbde" :weight bold)))
 '(org-document-title ((((type graphic)) :inherit alect-title)))
 '(org-document-info ((((type graphic)) :foreground "#fa5151")))
 '(org-document-info-keyword ((((type graphic)) :foreground "#e5c900")))
 '(org-formula ((((type graphic)) :foreground "#f8ffa0")))
 '(org-headline-done ((((type graphic)) :foreground "#2fdbde")))
 '(org-hide ((((type graphic)) :foreground "#222222")))
 '(org-level-1 ((((type graphic)) :inherit alect-title-1)))
 '(org-level-2 ((((type graphic)) :inherit alect-title-2)))
 '(org-level-3 ((((type graphic)) :inherit alect-title-3)))
 '(org-level-4 ((((type graphic)) :inherit alect-title-4)))
 '(org-level-5 ((((type graphic)) :inherit alect-title-5)))
 '(org-level-6 ((((type graphic)) :inherit alect-title-6)))
 '(org-level-7 ((((type graphic)) :inherit alect-title-7)))
 '(org-level-8 ((((type graphic)) :inherit alect-title-8)))
 '(org-link ((((type graphic)) :inherit link)))
 '(org-scheduled ((((type graphic)) :foreground "#8ce096")))
 '(org-scheduled-previously ((((type graphic)) :foreground "#fa6a6e")))
 '(org-scheduled-today ((((type graphic)) :foreground "#00aff5")))
 '(org-special-keyword ((((type graphic)) :inherit font-lock-doc-face)))
 '(org-table ((((type graphic)) :foreground "#d0bf8f")))
 '(org-tag ((((type graphic)) :slant italic)))
 '(org-time-grid ((((type graphic)) :foreground "#8c826d")))
 '(org-todo ((((type graphic)) :foreground "#ea3838" :weight bold)))
 '(org-upcoming-deadline ((((type graphic)) :inherit font-lock-keyword-face)))
 '(org-verbatim ((((type graphic)) :foreground "#8c826d")))
 '(org-warning ((((type graphic)) :foreground "#ea3838" :weight bold :underline nil)))
 '(org-column ((((type graphic)) :background "#222222")))
 '(org-column-title ((((type graphic)) :background "#222222" :underline t :weight bold)))
 '(outline-1 ((((type graphic)) :inherit alect-title-1)))
 '(outline-2 ((((type graphic)) :inherit alect-title-2)))
 '(outline-3 ((((type graphic)) :inherit alect-title-3)))
 '(outline-4 ((((type graphic)) :inherit alect-title-4)))
 '(outline-5 ((((type graphic)) :inherit alect-title-5)))
 '(outline-6 ((((type graphic)) :inherit alect-title-6)))
 '(outline-7 ((((type graphic)) :inherit alect-title-7)))
 '(outline-8 ((((type graphic)) :inherit alect-title-8)))
 '(popup-tip-face ((((type graphic)) :foreground "#000000" :background "#f8ffa0")))
 '(popup-scroll-bar-foreground-face ((((type graphic)) :background "#8c826d")))
 '(popup-scroll-bar-background-face ((((type graphic)) :background "#222222")))
 '(popup-isearch-match ((((type graphic)) :foreground "#d5d2be" :background "#3f3f3f")))
 '(rcirc-my-nick ((((type graphic)) :foreground "#62b6ea")))
 '(rcirc-other-nick ((((type graphic)) :foreground "#8c826d")))
 '(rcirc-bright-nick ((((type graphic)) :foreground "#00aff5")))
 '(rcirc-dim-nick ((((type graphic)) :foreground "#8cf1f1")))
 '(rcirc-server ((((type graphic)) :foreground "#7fb07f")))
 '(rcirc-server-prefix ((((type graphic)) :foreground "#3cb370")))
 '(rcirc-timestamp ((((type graphic)) :inherit alect-time)))
 '(rcirc-nick-in-message ((((type graphic)) :foreground "#fe8b04")))
 '(rcirc-nick-in-message-full-line ((((type graphic)) :weight bold)))
 '(rcirc-prompt ((((type graphic)) :inherit alect-prompt)))
 '(rcirc-track-nick ((((type graphic)) :inverse-video t)))
 '(rcirc-track-keyword ((((type graphic)) :weight bold)))
 '(rcirc-url ((((type graphic)) :weight bold)))
 '(rcirc-keyword ((((type graphic)) :foreground "#fe8b04" :weight bold)))
 '(rst-level-1 ((((type graphic)) :inherit alect-title-1)))
 '(rst-level-2 ((((type graphic)) :inherit alect-title-2)))
 '(rst-level-3 ((((type graphic)) :inherit alect-title-3)))
 '(rst-level-4 ((((type graphic)) :inherit alect-title-4)))
 '(rst-level-5 ((((type graphic)) :inherit alect-title-5)))
 '(rst-level-6 ((((type graphic)) :inherit alect-title-6)))
 '(rst-reference ((((type graphic)) :inherit link)))
 '(rst-adornment ((((type graphic)) :foreground "#f6f0e1")))
 '(rst-literal ((((type graphic)) :foreground "#528d8d")))
 '(ruler-mode-default ((((type graphic)) :inherit alect-tab-unselected :height 1.0)))
 '(ruler-mode-pad ((((type graphic)) :inherit ruler-mode-default)))
 '(ruler-mode-column-number ((((type graphic)) :inherit ruler-mode-default :foreground "#d5d2be")))
 '(ruler-mode-current-column ((((type graphic)) :inherit ruler-mode-default :background "#ffec8b" :foreground "#ffec8b")))
 '(ruler-mode-comment-column ((((type graphic)) :inherit (font-lock-comment-face ruler-mode-default))))
 '(ruler-mode-fill-column ((((type graphic)) :inherit ruler-mode-default :foreground "#ea3838" :weight bold)))
 '(ruler-mode-goal-column ((((type graphic)) :inherit ruler-mode-default :foreground "#fa5151")))
 '(ruler-mode-tab-stop ((((type graphic)) :inherit ruler-mode-default :foreground "#b2c3f8")))
 '(ruler-mode-fringes ((((type graphic)) :inherit ruler-mode-default :foreground "#7fb07f")))
 '(ruler-mode-margins ((((type graphic)) :inherit ruler-mode-default :foreground "#e353b9")))
 '(show-paren-mismatch ((((type graphic)) :foreground "#e9e9e9" :background "#ea3838")))
 '(show-paren-match ((((type graphic)) :foreground "#e9e9e9" :background "#3cb370")))
 '(vc-up-to-date-state ((((type graphic)) :foreground "#32cd32")))
 '(vc-edited-state ((((type graphic)) :foreground "#e5c900")))
 '(vc-missing-state ((((type graphic)) :foreground "#ea3838")))
 '(vc-conflict-state ((((type graphic)) :foreground "#c83029" :weight bold)))
 '(vc-locked-state ((((type graphic)) :foreground "#2fdbde")))
 '(vc-locally-added-state ((((type graphic)) :foreground "#62b6ea")))
 '(vc-needs-update-state ((((type graphic)) :foreground "#e353b9")))
 '(vc-removed-state ((((type graphic)) :foreground "#fa5151")))
 '(whitespace-space ((((type graphic)) :foreground "#5f5f5f")))
 '(whitespace-hspace ((((type graphic)) :background "#4f4f4f" :foreground "#fe8b04")))
 '(whitespace-tab ((((type graphic)) :background "#5f5f5f" :foreground "#b2c3f8")))
 '(whitespace-newline ((((type graphic)) :foreground "#b2c3f8")))
 '(whitespace-trailing ((((type graphic)) :inherit trailing-whitespace)))
 '(whitespace-line ((((type graphic)) :background "#222222")))
 '(whitespace-empty ((((type graphic)) :background "#5f5f5f")))
 '(whitespace-indentation ((((type graphic)) :background "#5f5f5f" :foreground "#ea3838")))
 '(whitespace-space-before-tab ((((type graphic)) :background "#5f5f5f" :foreground "#7fb07f")))
 '(whitespace-space-after-tab ((((type graphic)) :background "#5f5f5f" :foreground "#62b6ea")))
 '(widget-field ((((type graphic)) :background "#4f4f4f" :box (:line-width -1 :color "#8c826d" :style nil))))
 '(widget-button ((((type graphic)) :inherit alect-button)))
 '(widget-button-pressed ((((type graphic)) :inherit alect-button-pressed)))
 '(widget-documentation ((((type graphic)) :foreground "#32cd32")))
 '(widget-inactive ((((type graphic)) :inherit shadow)))
 '(widget-single-line-field ((((type graphic)) :foreground "#f0dfaf" :inherit widget-field)))
 '(default ((((type graphic)) :foreground "#d5d2be" :background "#3f3f3f"))))

(provide-theme 'alect-dark)
