(deftheme spacemacs-dark
  "Created 2015-08-26.")

(custom-theme-set-faces
 'spacemacs-dark
 '(cursor ((((class color) (min-colors 89)) (:background "#e3dedd"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#e0211d"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#1f71ab"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#2aa198" :background "#293234"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#a45bad"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :bold t))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:bold ((class color) (min-colors 89)) :foreground "#237fbf"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#a45bad"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#bc6ec5"))))
 '(font-lock-reference-face ((((class color) (min-colors 89)) (:foreground "#a45bad"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#38a882" :bold t))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#7590db"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#dc752f" :background "#292b2e"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#292b2e" :foreground "#b2b2b2"))))
 '(highlight ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#100a14"))))
 '(hl-line ((((class color) (min-colors 89)) (:background "#212026"))))
 '(isearch ((((class color) (min-colors 89)) (:bold t :foreground "#292b2e" :background "#2f96dc"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#292b2e" :background "#2f96dc" :weight normal))))
 '(link ((((class color) (min-colors 89)) (:foreground "#2aa198" :underline t))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#c56ec3" :underline t))))
 '(match ((((class color) (min-colors 89)) (:background "#292b2e" :foreground "#2f96dc" :weight bold))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:bold t :foreground "#237fbf"))))
 '(popup-tip-face ((((class color) (min-colors 89)) (:background "#5d4d7a" :foreground "#b2b2b2" :bold nil :italic nil :underline nil))))
 '(region ((((class color) (min-colors 89)) (:background "#333c45"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#100a14"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:background "#86dc2f"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#86dc2f"))))
 '(tooltip ((((class color) (min-colors 89)) (:background "#5d4d7a" :foreground "#b2b2b2" :bold nil :italic nil :underline nil))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#0a0814"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#dc752f"))))
 '(company-echo-common ((((class color) (min-colors 89)) (:background "#b2b2b2" :foreground "#292b2e"))))
 '(company-preview ((((class color) (min-colors 89)) (:background "#292b2e" :foreground "#4f97d7"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:background "#212026" :foreground "#237fbf"))))
 '(company-preview-search ((((class color) (min-colors 89)) (:background "#212026" :foreground "#67b11d"))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:background "#212026"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:background "#c56ec3"))))
 '(company-tooltip ((((class color) (min-colors 89)) (:background "#5d4d7a" :foreground "#222226"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:background "#5d4d7a" :foreground "#2f96dc"))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:background "#5d4d7a" :foreground "#b2b2b2"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:foreground "#86dc2f"))))
 '(company-tooltip-mouse ((((class color) (min-colors 89)) (:inherit highlight))))
 '(company-tooltip-search ((((class color) (min-colors 89)) (:inherit match))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:background "#6b5d85" :bold t))))
 '(diff-added ((((class color) (min-colors 89)) :background nil :foreground "#67b11d")))
 '(diff-changed ((((class color) (min-colors 89)) :background nil :foreground "#2f96dc")))
 '(diff-indicator-added ((((class color) (min-colors 89)) :background nil :foreground "#67b11d")))
 '(diff-indicator-changed ((((class color) (min-colors 89)) :background nil :foreground "#2f96dc")))
 '(diff-indicator-removed ((((class color) (min-colors 89)) :background nil :foreground "#f2241f")))
 '(diff-refine-added ((((class color) (min-colors 89)) :background "#67b11d" :foreground "#0a0814")))
 '(diff-refine-changed ((((class color) (min-colors 89)) :background "#2f96dc" :foreground "#0a0814")))
 '(diff-refine-removed ((((class color) (min-colors 89)) :background "#f2241f" :foreground "#0a0814")))
 '(diff-removed ((((class color) (min-colors 89)) :background nil :foreground "#f2241f")))
 '(dired-directory ((((class color) (min-colors 89)) (:foreground "#4f97d7" :background "#292b2e" :weight bold))))
 '(dired-flagged ((((class color) (min-colors 89)) (:foreground "#f2241f"))))
 '(dired-header ((((class color) (min-colors 89)) (:foreground "#c56ec3" :weight bold))))
 '(dired-ignored ((((class color) (min-colors 89)) (:inherit shadow))))
 '(dired-mark ((((class color) (min-colors 89)) (:foreground "#c56ec3" :weight bold))))
 '(dired-marked ((((class color) (min-colors 89)) (:foreground "#a31db1" :weight bold))))
 '(dired-perm-write ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :underline t))))
 '(dired-symlink ((((class color) (min-colors 89)) (:foreground "#28def0" :background "#292b2e" :weight bold))))
 '(dired-warning ((((class color) (min-colors 89)) (:foreground "#dc752f"))))
 '(ediff-current-diff-A ((((class color) (min-colors 89)) (:background "#293239" :foreground "#2f96dc"))))
 '(ediff-current-diff-Ancestor ((((class color) (min-colors 89)) (:background "#293235" :foreground "#2aa198"))))
 '(ediff-current-diff-B ((((class color) (min-colors 89)) (:background "#32322c" :foreground "#b1951d"))))
 '(ediff-current-diff-C ((((class color) (min-colors 89)) (:background "#2d332c" :foreground "#67b11d"))))
 '(ediff-even-diff-A ((((class color) (min-colors 89)) (:background "#100a14"))))
 '(ediff-even-diff-Ancestor ((((class color) (min-colors 89)) (:background "#100a14"))))
 '(ediff-even-diff-B ((((class color) (min-colors 89)) (:background "#100a14"))))
 '(ediff-even-diff-C ((((class color) (min-colors 89)) (:background "#100a14"))))
 '(ediff-fine-diff-A ((((class color) (min-colors 89)) (:background nil :bold t :underline t))))
 '(ediff-fine-diff-Ancestor ((((class color) (min-colors 89)) (:background nil :bold t :underline t))))
 '(ediff-fine-diff-B ((((class color) (min-colors 89)) (:background nil :bold t :underline t))))
 '(ediff-fine-diff-C ((((class color) (min-colors 89)) (:background nil :bold t :underline t))))
 '(ediff-odd-diff-A ((((class color) (min-colors 89)) (:background "#0a0814"))))
 '(ediff-odd-diff-Ancestor ((((class color) (min-colors 89)) (:background "#0a0814"))))
 '(ediff-odd-diff-B ((((class color) (min-colors 89)) (:background "#0a0814"))))
 '(ediff-odd-diff-C ((((class color) (min-colors 89)) (:background "#0a0814"))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:foreground "#86dc2f" :bold t))))
 '(flycheck-error ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#e0211d"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#e0211d" :weight bold :underline t))))
 '(flycheck-error-list-checker-name ((((class color) (min-colors 89)) (:foreground "#237fbf"))))
 '(flycheck-fringe-error ((((class color) (min-colors 89)) (:foreground "#e0211d" :weight bold))))
 '(flycheck-fringe-info ((((class color) (min-colors 89)) (:foreground "#2f96dc" :weight bold))))
 '(flycheck-fringe-warning ((((class color) (min-colors 89)) (:foreground "#dc752f" :weight bold))))
 '(flycheck-info ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#2f96dc"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#2f96dc" :weight bold :underline t))))
 '(flycheck-warning ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#dc752f"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#dc752f" :weight bold :underline t))))
 '(gnus-summary-cancelled ((((class color) (min-colors 89)) (:background "#e0211d" :foreground "#292b2e"))))
 '(helm-bookmark-directory ((((class color) (min-colors 89)) (:inherit helm-ff-directory))))
 '(helm-bookmark-file ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(helm-bookmark-gnus ((((class color) (min-colors 89)) (:foreground "#c56ec3"))))
 '(helm-bookmark-info ((((class color) (min-colors 89)) (:foreground "#c56ec3"))))
 '(helm-bookmark-man ((((class color) (min-colors 89)) (:foreground "#c56ec3"))))
 '(helm-bookmark-w3m ((((class color) (min-colors 89)) (:foreground "#c56ec3"))))
 '(helm-buffer-directory ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#292b2e"))))
 '(helm-buffer-file ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#292b2e"))))
 '(helm-buffer-not-saved ((((class color) (min-colors 89)) (:foreground "#c56ec3" :background "#292b2e"))))
 '(helm-buffer-process ((((class color) (min-colors 89)) (:foreground "#1f71ab" :background "#292b2e"))))
 '(helm-buffer-saved-out ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#292b2e"))))
 '(helm-buffer-size ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#292b2e"))))
 '(helm-candidate-number ((((class color) (min-colors 89)) (:background "#292b2e" :foreground "#2f96dc" :bold t))))
 '(helm-ff-directory ((((class color) (min-colors 89)) (:foreground "#4f97d7" :background "#292b2e" :weight bold))))
 '(helm-ff-dotted-directory ((((class color) (min-colors 89)) (:foreground "#4f97d7" :background "#292b2e" :weight bold))))
 '(helm-ff-executable ((((class color) (min-colors 89)) (:foreground "#86dc2f" :background "#292b2e" :weight normal))))
 '(helm-ff-file ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#292b2e" :weight normal))))
 '(helm-ff-invalid-symlink ((((class color) (min-colors 89)) (:foreground "#f2241f" :background "#292b2e" :weight bold))))
 '(helm-ff-prefix ((((class color) (min-colors 89)) (:foreground "#292b2e" :background "#237fbf" :weight normal))))
 '(helm-ff-symlink ((((class color) (min-colors 89)) (:foreground "#28def0" :background "#292b2e" :weight bold))))
 '(helm-grep-cmd-line ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#292b2e"))))
 '(helm-grep-file ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#292b2e"))))
 '(helm-grep-finish ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#292b2e"))))
 '(helm-grep-lineno ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#292b2e"))))
 '(helm-grep-match ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit helm-match))))
 '(helm-grep-running ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :background "#292b2e"))))
 '(helm-header ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#292b2e" :underline nil :box nil))))
 '(helm-header-line-left-margin ((((class color) (min-colors 89)) (:foreground "#2f96dc" :background nil))))
 '(helm-match ((((class color) (min-colors 89)) (:inherit match))))
 '(helm-match-item ((((class color) (min-colors 89)) (:inherit match))))
 '(helm-moccur-buffer ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :background "#292b2e"))))
 '(helm-selection ((((class color) (min-colors 89)) (:background "#333c45"))))
 '(helm-selection-line ((((class color) (min-colors 89)) (:background "#212026"))))
 '(helm-separator ((((class color) (min-colors 89)) (:foreground "#c56ec3" :background "#292b2e"))))
 '(helm-source-header ((((class color) (min-colors 89)) (:background "#c56ec3" :foreground "#292b2e" :bold t))))
 '(helm-visible-mark ((((class color) (min-colors 89)) (:foreground "#292b2e" :background "#100a14"))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#c56ec3" :bold t))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#86dc2f" :bold t))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(info-header-xref ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :underline t))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :bold t))))
 '(info-title-1 ((((class color) (min-colors 89)) (:height 1.4 :bold t))))
 '(info-title-2 ((((class color) (min-colors 89)) (:height 1.3 :bold t))))
 '(info-title-3 ((((class color) (min-colors 89)) (:height 1.3))))
 '(info-title-4 ((((class color) (min-colors 89)) (:height 1.2))))
 '(linum ((((class color) (min-colors 89)) (:foreground "#2aa198" :background "#212026"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#222226" :box (:color "#5d4d7a" :line-width 1)))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#292b2e" :box (:color "#5d4d7a" :line-width 1)))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:bold t :foreground "#bc6ec5"))))
 '(org-agenda-clocking ((((class color) (min-colors 89)) (:foreground "#c56ec3"))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#7590db" :height 1.1))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:weight bold :foreground "#237fbf" :height 1.3))))
 '(org-agenda-date-weekend ((((class color) (min-colors 89)) (:weight normal :foreground "#7590db"))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#86dc2f" :bold t))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:weight bold :foreground "#c56ec3"))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(org-clock-overlay ((((class color) (min-colors 89)) (:foreground "#c56ec3"))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#28def0"))))
 '(org-column ((((class color) (min-colors 89)) (:background "#333c45"))))
 '(org-column-title ((((class color) (min-colors 89)) (:background "#333c45"))))
 '(org-date ((((class color) (min-colors 89)) (:underline t :foreground "#7590db"))))
 '(org-date-selected ((((class color) (min-colors 89)) (:background "#bc6ec5" :foreground "#292b2e"))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(org-document-title ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :weight bold :height 1.4 :underline t))))
 '(org-done ((((class color) (min-colors 89)) (:foreground "#86dc2f" :bold t :overline t :background "#2d332c"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#1f71ab"))))
 '(org-footnote ((((class color) (min-colors 89)) (:underline t :foreground "#b2b2b2"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(org-level-1 ((((class color) (min-colors 89)) (:bold t :foreground "#2f96dc" :height 1.3 :background "#293239" :overline t))))
 '(org-level-2 ((((class color) (min-colors 89)) (:bold t :foreground "#2aa198" :height 1.2 :background "#293235"))))
 '(org-level-3 ((((class color) (min-colors 89)) (:bold nil :foreground "#67b11d" :height 1.1 :background "#2d332c"))))
 '(org-level-4 ((((class color) (min-colors 89)) (:bold nil :foreground "#b1951d" :background "#32322c"))))
 '(org-level-5 ((((class color) (min-colors 89)) (:bold nil :foreground "#2f96dc"))))
 '(org-level-6 ((((class color) (min-colors 89)) (:bold nil :foreground "#2aa198"))))
 '(org-level-7 ((((class color) (min-colors 89)) (:bold nil :foreground "#67b11d"))))
 '(org-level-8 ((((class color) (min-colors 89)) (:bold nil :foreground "#b1951d"))))
 '(org-link ((((class color) (min-colors 89)) (:underline t :foreground "#2aa198"))))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 89)) (:foreground "#e0211d"))))
 '(org-priority ((((class color) (min-colors 89)) (:foreground "#dc752f" :bold t))))
 '(org-quote ((((class color) (min-colors 89)) (:inherit org-block :slant italic))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#c56ec3"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :weight bold :height 1.2))))
 '(org-sexp-date ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#bc6ec5"))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#b1951d" :background "#32322c"))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#dc752f" :bold t :overline t :background "#32322c"))))
 '(org-verbatim ((((class color) (min-colors 89)) (:foreground "#2f96dc"))))
 '(org-verse ((((class color) (min-colors 89)) (:inherit org-block :slant italic))))
 '(org-warning ((((class color) (min-colors 89)) (:foreground "#e0211d"))))
 '(powerline-active1 ((((class color) (min-colors 89)) (:background "#5d4d7a" :foreground "#b2b2b2"))))
 '(powerline-active2 ((((class color) (min-colors 89)) (:background "#5d4d7a" :foreground "#b2b2b2"))))
 '(powerline-inactive1 ((((class color) (min-colors 89)) (:background "#212026" :foreground "#b2b2b2"))))
 '(powerline-inactive2 ((((class color) (min-colors 89)) (:background "#212026" :foreground "#b2b2b2"))))
 '(which-key-command-description-face ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(which-key-group-description-face ((((class color) (min-colors 89)) (:foreground "#277bb8"))))
 '(which-key-key-face ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :bold t))))
 '(which-key-separator-face ((((class color) (min-colors 89)) (:background nil :foreground "#2aa198"))))
 '(which-key-special-key-face ((((class color) (min-colors 89)) (:background "#bc6ec5" :foreground "#292b2e"))))
 '(ac-completion-face ((((class color) (min-colors 89)) (:underline t :foreground "#237fbf"))))
 '(ffap ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(font-latex-bold-face ((((class color) (min-colors 89)) (:foreground "#c56ec3"))))
 '(font-latex-italic-face ((((class color) (min-colors 89)) (:foreground "#277bb8" :italic t))))
 '(font-latex-string-face ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(icompletep-determined ((((class color) (min-colors 89)) :foreground "#1f71ab")))
 '(trailing-whitespace ((((class color) (min-colors 89)) :foreground nil :background "#e0211d")))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) :foreground "#1f71ab")))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) :foreground "#b2b2b2")))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) :foreground "#c56ec3")))
 '(undo-tree-visualizer-unmodified-face ((((class color) (min-colors 89)) :foreground "#7590db")))
 '(default ((((class color) (min-colors 89)) (:background "#292b2e" :foreground "#b2b2b2")))))

(provide-theme 'spacemacs-dark)
