(deftheme alect-light
  "Created 2015-08-27.")

(custom-theme-set-variables
 'alect-light
 '(ansi-color-names-vector ["#ded6c5" "#f71010" "#028902" "#ef8300" "#0000ff" "#a020f0" "#358d8d" "#262626"])
 '(gnus-mode-line-image-cache (quote (image :type xpm :ascent center :data "/* XPM */
static char *gnus-pointer[] = {
/* width height num_colors chars_per_pixel */
\"    18    13        2            1\",
/* colors */
\". c #358d8d\",
\"# c None s None\",
/* pixels */
\"##################\",
\"######..##..######\",
\"#####........#####\",
\"#.##.##..##...####\",
\"#...####.###...##.\",
\"#..###.######.....\",
\"#####.########...#\",
\"###########.######\",
\"####.###.#..######\",
\"######..###.######\",
\"###....####.######\",
\"###..######.######\",
\"###########.######\" };")))
 '(gnus-logo-colors (quote ("#0d7b72" "#adadad")))
 '(diary-entry-marker (quote font-lock-variable-name-face)))

(custom-theme-set-faces
 'alect-light
 '(cursor ((((type graphic)) :background "#1074cd")))
 '(button ((((type graphic)) :inherit link :underline (:color "#262626"))))
 '(link ((((type graphic)) :foreground "#2c53ca" :underline t)))
 '(link-visited ((((type graphic)) :foreground "#00008b" :underline t)))
 '(match ((((type graphic)) :background "#008b45" :foreground "#fafafa")))
 '(escape-glyph ((((type graphic)) :foreground "#ef8300" :weight bold)))
 '(fringe ((((type graphic)) :foreground "#909090" :background "#f6f0e1")))
 '(header-line ((((type graphic)) :foreground "#101010" :height 1.13 :box (:line-width 1 :color "#101010" :style nil))))
 '(highlight ((((type graphic)) :foreground "#070707" :background "#fafafa")))
 '(shadow ((((type graphic)) :foreground "#909090")))
 '(success ((((type graphic)) :foreground "#028902" :weight bold)))
 '(error ((((type graphic)) :foreground "#f71010" :weight bold)))
 '(warning ((((type graphic)) :foreground "#9ca30b")))
 '(region ((((type graphic)) :background "#ccc19b")))
 '(menu ((((type graphic)) :foreground "#101010" :background "#f6f0e1" :height 1.13)))
 '(tool-bar ((((type graphic)) :inherit mode-line)))
 '(scroll-bar ((((type graphic)) :background "#ccc19b")))
 '(tooltip ((((type graphic)) :inherit variable-pitch :foreground "#286060" :background "#f6f0e1")))
 '(minibuffer-prompt ((((type graphic)) :inherit alect-prompt)))
 '(secondary-selection ((((type graphic)) :background "#d3c7a0")))
 '(trailing-whitespace ((((type graphic)) :background "#f71010")))
 '(vertical-border ((((type graphic)) :foreground "#262626")))
 '(window-divider ((((type graphic)) :foreground "#077707")))
 '(window-divider-first-pixel ((((type graphic)) :foreground "#008b45")))
 '(window-divider-last-pixel ((((type graphic)) :inherit window-divider-first-pixel)))
 '(alect-prompt ((((type graphic)) :foreground "#ba55d3" :weight bold)))
 '(alect-time ((((type graphic)) :foreground "#0eaeae")))
 '(alect-author ((((type graphic)) :foreground "#ba55d3")))
 '(alect-key ((((type graphic)) :foreground "#fa5151" :weight bold)))
 '(alect-selected-item ((((type graphic)) :background "#d9ceb2" :box (:line-width -1 :color "#262626" :style nil))))
 '(alect-color-level-1 ((((type graphic)) :foreground "#0505cc")))
 '(alect-color-level-2 ((((type graphic)) :foreground "#028902")))
 '(alect-color-level-3 ((((type graphic)) :foreground "#d81212")))
 '(alect-color-level-4 ((((type graphic)) :foreground "#6a621b")))
 '(alect-color-level-5 ((((type graphic)) :foreground "#0d7b72")))
 '(alect-color-level-6 ((((type graphic)) :foreground "#2c53ca")))
 '(alect-color-level-7 ((((type graphic)) :foreground "#ba55d3")))
 '(alect-color-level-8 ((((type graphic)) :foreground "#ef8300")))
 '(alect-color-level-9 ((((type graphic)) :foreground "#1c9e28")))
 '(alect-color-level-10 ((((type graphic)) :foreground "#fa5151")))
 '(alect-color-level-11 ((((type graphic)) :foreground "#0eaeae")))
 '(alect-color-level-12 ((((type graphic)) :foreground "#8b008b")))
 '(alect-title ((((type graphic)) :foreground "#077707" :weight bold :height 1.13)))
 '(alect-title-1 ((((type graphic)) :inherit alect-color-level-1 :weight bold :height 1.13)))
 '(alect-title-2 ((((type graphic)) :inherit alect-color-level-2 :weight bold :height 1.13)))
 '(alect-title-3 ((((type graphic)) :inherit alect-color-level-3 :weight bold :height 1.13)))
 '(alect-title-4 ((((type graphic)) :inherit alect-color-level-4 :weight bold :height 1.13)))
 '(alect-title-5 ((((type graphic)) :inherit alect-color-level-5 :weight bold :height 1.13)))
 '(alect-title-6 ((((type graphic)) :inherit alect-color-level-6 :weight bold :height 1.13)))
 '(alect-title-7 ((((type graphic)) :inherit alect-color-level-7 :weight bold :height 1.13)))
 '(alect-title-8 ((((type graphic)) :inherit alect-color-level-8 :weight bold :height 1.13)))
 '(alect-button ((((type graphic)) :foreground "#101010" :background "#ccc19b" :box (:line-width 2 :style released-button))))
 '(alect-button-pressed ((((type graphic)) :inherit alect-button :box (:line-width 2 :style pressed-button))))
 '(alect-button-mouse ((((type graphic)) :inherit highlight :box (:line-width 2 :style released-button))))
 '(alect-tab-default ((((type graphic)) :height 0.9 :box nil)))
 '(alect-tab-unselected ((((type graphic)) :inherit alect-tab-default :foreground "#6c6c6c" :background "#d9ceb2" :box (:line-width 1 :style released-button))))
 '(alect-tab-selected ((((type graphic)) :inherit alect-tab-unselected :foreground "#101010" :background "#d3c7a0")))
 '(alect-tab-mouse ((((type graphic)) :inherit alect-tab-default :inherit mode-line-highlight)))
 '(apropos-keybinding ((((type graphic)) :inherit alect-key)))
 '(apropos-symbol ((((type graphic)) :foreground "#008b45" :weight bold)))
 '(ac-candidate-face ((((type graphic)) :foreground "#070707" :background "#ccc19b")))
 '(ac-selection-face ((((type graphic)) :foreground "#ded6c5" :background "#262626")))
 '(ac-completion-face ((((type graphic)) :foreground "#6c6c6c")))
 '(ac-candidate-mouse-face ((((type graphic)) :inherit highlight)))
 '(calendar-today ((((type graphic)) :box (:line-width -1 :color "#f71010" :style nil))))
 '(diary ((((type graphic)) :foreground "#077707" :weight bold)))
 '(holiday ((((type graphic)) :background "#ccc19b")))
 '(change-log-date ((((type graphic)) :inherit alect-time)))
 '(change-log-name ((((type graphic)) :inherit alect-author)))
 '(change-log-email ((((type graphic)) :foreground "#fa5151")))
 '(change-log-file ((((type graphic)) :foreground "#1c9e28")))
 '(change-log-list ((((type graphic)) :inherit font-lock-function-name-face)))
 '(change-log-conditionals ((((type graphic)) :inherit font-lock-variable-name-face)))
 '(change-log-function ((((type graphic)) :foreground "#ef8300")))
 '(change-log-acknowledgment ((((type graphic)) :inherit font-lock-keyword-face)))
 '(comint-highlight-prompt ((((type graphic)) :inherit alect-prompt)))
 '(comint-highlight-input ((((type graphic)) :weight bold)))
 '(company-tooltip ((((type graphic)) :foreground "#505050" :background "#d3c7a0")))
 '(company-tooltip-selection ((((type graphic)) :foreground "#505050" :background "#f6f0e1")))
 '(company-tooltip-mouse ((((type graphic)) :inherit highlight)))
 '(company-tooltip-annotation ((((type graphic)) :inherit company-tooltip :foreground "#0000ff")))
 '(company-tooltip-common ((((type graphic)) :inherit company-tooltip :foreground "#262626")))
 '(company-tooltip-common-selection ((((type graphic)) :inherit company-tooltip-selection :foreground "#262626")))
 '(company-preview ((((type graphic)) :foreground "#505050")))
 '(company-preview-common ((((type graphic)) :inherit company-preview :underline t)))
 '(company-scrollbar-fg ((((type graphic)) :background "#444444")))
 '(company-scrollbar-bg ((((type graphic)) :background "#909090")))
 '(compilation-info ((((type graphic)) :foreground "#3cb368")))
 '(compilation-warning ((((type graphic)) :inherit warning)))
 '(compilation-error ((((type graphic)) :inherit error)))
 '(compilation-line-number ((((type graphic)) :foreground "#ef8300")))
 '(compilation-column-number ((((type graphic)) :foreground "#6a621b")))
 '(compilation-mode-line-run ((((type graphic)) :foreground "#0000ff")))
 '(compilation-mode-line-exit ((((type graphic)) :inherit success)))
 '(compilation-mode-line-fail ((((type graphic)) :inherit compilation-error)))
 '(cperl-hash-face ((((type graphic)) :foreground "#0d7b72")))
 '(cperl-array-face ((((type graphic)) :foreground "#9ca30b")))
 '(cperl-nonoverridable-face ((((type graphic)) :foreground "#1c9e28")))
 '(custom-button ((((type graphic)) :inherit alect-button)))
 '(custom-button-pressed ((((type graphic)) :inherit alect-button-pressed)))
 '(custom-button-mouse ((((type graphic)) :inherit alect-button-mouse)))
 '(custom-button-unraised ((((type graphic)) :inherit alect-button :box nil)))
 '(custom-button-pressed-unraised ((((type graphic)) :inherit custom-button-unraised :underline t)))
 '(custom-documentation ((((type graphic)) :inherit font-lock-doc-face)))
 '(custom-comment ((((type graphic)) :foreground "#909090")))
 '(custom-state ((((type graphic)) :foreground "#008b45")))
 '(custom-link ((((type graphic)) :inherit link)))
 '(custom-group-tag ((((type graphic)) :inherit alect-title-1)))
 '(custom-group-tag-1 ((((type graphic)) :inherit alect-title-2)))
 '(custom-group-subtitle ((((type graphic)) :inherit alect-title-3)))
 '(custom-face-tag ((((type graphic)) :foreground "#9400d3" :weight bold)))
 '(custom-variable-tag ((((type graphic)) :inherit font-lock-variable-name-face :weight bold)))
 '(custom-variable-button ((((type graphic)) :weight bold :underline t)))
 '(custom-visibility ((((type graphic)) :inherit link :height 0.8)))
 '(diff-context ((((type graphic)) :foreground "#505050")))
 '(diff-added ((((type graphic)) :foreground "#1c9e28")))
 '(diff-changed ((((type graphic)) :foreground "#9ca30b")))
 '(diff-removed ((((type graphic)) :foreground "#e43838")))
 '(diff-indicator-added ((((type graphic)) :inherit diff-added)))
 '(diff-indicator-changed ((((type graphic)) :inherit diff-changed)))
 '(diff-indicator-removed ((((type graphic)) :inherit diff-removed)))
 '(diff-refine-added ((((type graphic)) :inherit diff-added :underline t)))
 '(diff-refine-changed ((((type graphic)) :inherit diff-changed :underline t)))
 '(diff-refine-removed ((((type graphic)) :inherit diff-removed :underline t)))
 '(diff-header ((((type graphic)) :foreground "#0092ff" :weight bold)))
 '(diff-hunk-header ((((type graphic)) :inherit diff-header :foreground "#077707")))
 '(diff-file-header ((((type graphic)) :inherit diff-header :foreground "#259ea2")))
 '(diff-function ((((type graphic)) :inherit diff-header :foreground "#0000ff")))
 '(diff-index ((((type graphic)) :inherit diff-header :foreground "#e43838")))
 '(diff-nonexistent ((((type graphic)) :inherit diff-header :foreground "#909090")))
 '(dired-directory ((((type graphic)) :inherit font-lock-function-name-face)))
 '(dired-flagged ((((type graphic)) :foreground "#f71010")))
 '(dired-header ((((type graphic)) :inherit alect-title)))
 '(dired-ignored ((((type graphic)) :foreground "#909090")))
 '(dired-mark ((((type graphic)) :foreground "#0505cc")))
 '(dired-marked ((((type graphic)) :inherit warning)))
 '(dired-perm-write ((((type graphic)) :foreground "#1c9e28")))
 '(dired-symlink ((((type graphic)) :inherit font-lock-constant-face)))
 '(dired-warning ((((type graphic)) :inherit font-lock-warning-face :background "#f6f0e1")))
 '(ediff-even-diff-A ((((type graphic)) :background "#d9ceb2")))
 '(ediff-odd-diff-A ((((type graphic)) :background "#d3c7a0")))
 '(ediff-even-diff-B ((((type graphic)) :inherit ediff-even-diff-A)))
 '(ediff-odd-diff-B ((((type graphic)) :inherit ediff-odd-diff-A)))
 '(ediff-even-diff-C ((((type graphic)) :inherit ediff-even-diff-A)))
 '(ediff-odd-diff-C ((((type graphic)) :inherit ediff-odd-diff-A)))
 '(eldoc-highlight-function-argument ((((type graphic)) :foreground "#028902" :weight bold)))
 '(erc-bold-face ((((type graphic)) :weight bold)))
 '(erc-current-nick-face ((((type graphic)) :foreground "#0000ff" :weight bold)))
 '(erc-default-face ((((type graphic)) :foreground "#262626")))
 '(erc-direct-msg-face ((((type graphic)) :inherit erc-default-face :foreground "#fa5151")))
 '(erc-action-face ((((type graphic)) :inherit erc-bold-face)))
 '(erc-error-face ((((type graphic)) :inherit error)))
 '(erc-highlight-face ((((type graphic)) :inherit hover-highlight)))
 '(erc-input-face ((((type graphic)) :background "#d3c7a0")))
 '(erc-keyword-face ((((type graphic)) :foreground "#008b45")))
 '(erc-notice-face ((((type graphic)) :foreground "#028902")))
 '(erc-pal-face ((((type graphic)) :foreground "#8b008b")))
 '(erc-prompt-face ((((type graphic)) :inherit alect-prompt)))
 '(epa-mark ((((type graphic)) :foreground "#0505cc")))
 '(epa-string ((((type graphic)) :foreground "#286060")))
 '(epa-validity-disabled ((((type graphic)) :foreground "#6c6c6c")))
 '(epa-validity-high ((((type graphic)) :foreground "#1c9e28")))
 '(epa-validity-medium ((((type graphic)) :foreground "#9ca30b")))
 '(epa-validity-low ((((type graphic)) :foreground "#e43838")))
 '(eshell-prompt ((((type graphic)) :inherit alect-prompt)))
 '(eshell-ls-archive ((((type graphic)) :foreground "#028902")))
 '(eshell-ls-backup ((((type graphic)) :inherit dired-ignored)))
 '(eshell-ls-clutter ((((type graphic)) :inherit font-lock-comment-face)))
 '(eshell-ls-directory ((((type graphic)) :inherit dired-directory)))
 '(eshell-ls-executable ((((type graphic)) :foreground "#ef8300")))
 '(eshell-ls-unreadable ((((type graphic)) :foreground "#fa5151")))
 '(eshell-ls-readonly ((((type graphic)) :foreground "#6c6c6c")))
 '(eshell-ls-missing ((((type graphic)) :inherit dired-warning)))
 '(eshell-ls-product ((((type graphic)) :inherit font-lock-doc-face)))
 '(eshell-ls-special ((((type graphic)) :foreground "#262626" :weight bold)))
 '(eshell-ls-symlink ((((type graphic)) :inherit dired-symlink)))
 '(flymake-errline ((((type graphic)) :foreground "#e43838" :weight bold :underline t)))
 '(flymake-warnline ((((type graphic)) :foreground "#6c6c6c" :weight bold :underline t)))
 '(flyspell-duplicate ((((type graphic)) :foreground "#909090" :underline (:color "#101010"))))
 '(flyspell-incorrect ((((type graphic)) :inherit flyspell-duplicate :foreground "#d81212")))
 '(font-lock-builtin-face ((((type graphic)) :foreground "#ba55d3")))
 '(font-lock-comment-face ((((type graphic)) :foreground "#008b45")))
 '(font-lock-comment-delimiter-face ((((type graphic)) :inherit font-lock-comment-face)))
 '(font-lock-constant-face ((((type graphic)) :foreground "#259ea2")))
 '(font-lock-doc-face ((((type graphic)) :foreground "#505050" :slant italic)))
 '(font-lock-function-name-face ((((type graphic)) :foreground "#2c53ca")))
 '(font-lock-keyword-face ((((type graphic)) :foreground "#0505cc" :weight bold)))
 '(font-lock-negation-char-face ((((type graphic)) :foreground "#0000ff")))
 '(font-lock-preprocessor-face ((((type graphic)) :foreground "#1c9e28")))
 '(font-lock-string-face ((((type graphic)) :foreground "#fa5151")))
 '(font-lock-type-face ((((type graphic)) :foreground "#9400d3")))
 '(font-lock-variable-name-face ((((type graphic)) :foreground "#6a621b")))
 '(font-lock-warning-face ((((type graphic)) :foreground "#f71010" :weight bold)))
 '(font-lock-regexp-grouping-backslash ((((type graphic)) :foreground "#b22222")))
 '(font-lock-regexp-grouping-construct ((((type graphic)) :foreground "#9ca30b")))
 '(gnus-group-news-1-empty ((((type graphic)) :inherit alect-color-level-1)))
 '(gnus-group-news-2-empty ((((type graphic)) :inherit alect-color-level-2)))
 '(gnus-group-news-3-empty ((((type graphic)) :inherit alect-color-level-3)))
 '(gnus-group-news-4-empty ((((type graphic)) :inherit alect-color-level-4)))
 '(gnus-group-news-5-empty ((((type graphic)) :inherit alect-color-level-5)))
 '(gnus-group-news-6-empty ((((type graphic)) :inherit alect-color-level-6)))
 '(gnus-group-news-low-empty ((((type graphic)) :inherit alect-color-level-7)))
 '(gnus-group-news-1 ((((type graphic)) :inherit gnus-group-news-1-empty :weight bold)))
 '(gnus-group-news-2 ((((type graphic)) :inherit gnus-group-news-2-empty :weight bold)))
 '(gnus-group-news-3 ((((type graphic)) :inherit gnus-group-news-3-empty :weight bold)))
 '(gnus-group-news-4 ((((type graphic)) :inherit gnus-group-news-4-empty :weight bold)))
 '(gnus-group-news-5 ((((type graphic)) :inherit gnus-group-news-5-empty :weight bold)))
 '(gnus-group-news-6 ((((type graphic)) :inherit gnus-group-news-6-empty :weight bold)))
 '(gnus-group-news-low ((((type graphic)) :inherit gnus-group-news-low-empty :weight bold)))
 '(gnus-group-mail-1-empty ((((type graphic)) :inherit gnus-group-news-1-empty :slant italic)))
 '(gnus-group-mail-2-empty ((((type graphic)) :inherit gnus-group-news-2-empty :slant italic)))
 '(gnus-group-mail-3-empty ((((type graphic)) :inherit gnus-group-news-3-empty :slant italic)))
 '(gnus-group-mail-low-empty ((((type graphic)) :inherit gnus-group-news-low-empty :slant italic)))
 '(gnus-group-mail-1 ((((type graphic)) :inherit gnus-group-news-1 :slant italic)))
 '(gnus-group-mail-2 ((((type graphic)) :inherit gnus-group-news-2 :slant italic)))
 '(gnus-group-mail-3 ((((type graphic)) :inherit gnus-group-news-3 :slant italic)))
 '(gnus-group-mail-low ((((type graphic)) :inherit gnus-group-news-low :slant italic)))
 '(gnus-header-content ((((type graphic)) :inherit message-header-other)))
 '(gnus-header-from ((((type graphic)) :foreground "#e43838")))
 '(gnus-header-name ((((type graphic)) :inherit message-header-name)))
 '(gnus-header-newsgroups ((((type graphic)) :inherit message-header-newsgroups)))
 '(gnus-header-subject ((((type graphic)) :inherit message-header-subject)))
 '(gnus-summary-cancelled ((((type graphic)) :background "#505050" :foreground "#f6f0e1")))
 '(gnus-summary-low-ancient ((((type graphic)) :foreground "#0092ff")))
 '(gnus-summary-low-read ((((type graphic)) :foreground "#3cb368")))
 '(gnus-summary-low-ticked ((((type graphic)) :foreground "#fa5151")))
 '(gnus-summary-low-unread ((((type graphic)) :foreground "#505050")))
 '(gnus-summary-normal-ancient ((((type graphic)) :foreground "#0000ff")))
 '(gnus-summary-normal-read ((((type graphic)) :foreground "#028902")))
 '(gnus-summary-normal-ticked ((((type graphic)) :foreground "#f71010")))
 '(gnus-summary-normal-unread ((((type graphic)) :foreground "#262626")))
 '(gnus-summary-high-ancient ((((type graphic)) :inherit gnus-summary-normal-ancient :weight bold)))
 '(gnus-summary-high-read ((((type graphic)) :inherit gnus-summary-normal-read :weight bold)))
 '(gnus-summary-high-ticked ((((type graphic)) :inherit gnus-summary-normal-ticked :weight bold)))
 '(gnus-summary-high-unread ((((type graphic)) :inherit gnus-summary-normal-unread :weight bold)))
 '(gnus-summary-selected ((((type graphic)) :inherit alect-selected-item)))
 '(gnus-cite-1 ((((type graphic)) :inherit alect-color-level-1)))
 '(gnus-cite-2 ((((type graphic)) :inherit alect-color-level-2)))
 '(gnus-cite-3 ((((type graphic)) :inherit alect-color-level-3)))
 '(gnus-cite-4 ((((type graphic)) :inherit alect-color-level-4)))
 '(gnus-cite-5 ((((type graphic)) :inherit alect-color-level-5)))
 '(gnus-cite-6 ((((type graphic)) :inherit alect-color-level-6)))
 '(gnus-cite-7 ((((type graphic)) :inherit alect-color-level-7)))
 '(gnus-cite-8 ((((type graphic)) :inherit alect-color-level-8)))
 '(gnus-cite-9 ((((type graphic)) :inherit alect-color-level-9)))
 '(gnus-cite-10 ((((type graphic)) :inherit alect-color-level-10)))
 '(gnus-cite-11 ((((type graphic)) :inherit alect-color-level-11)))
 '(gnus-signature ((((type graphic)) :foreground "#0d7b72")))
 '(gnus-server-agent ((((type graphic)) :foreground "#8b008b")))
 '(gnus-server-closed ((((type graphic)) :foreground "#0000ff")))
 '(gnus-server-denied ((((type graphic)) :inherit font-lock-warning-face)))
 '(gnus-server-offline ((((type graphic)) :foreground "#9ca30b")))
 '(gnus-server-opened ((((type graphic)) :foreground "#028902")))
 '(helm-header ((((type graphic)) :inherit header-line)))
 '(helm-source-header ((((type graphic)) :inherit alect-title)))
 '(helm-separator ((((type graphic)) :foreground "#00008b")))
 '(helm-M-x-key ((((type graphic)) :foreground "#ef8300")))
 '(helm-selection ((((type graphic)) :background "#d9ceb2")))
 '(helm-selection-line ((((type graphic)) :background "#d9ceb2")))
 '(helm-visible-mark ((((type graphic)) :foreground "#9ca30b")))
 '(helm-candidate-number ((((type graphic)) :background "#f6f0e1" :foreground "#3cb368")))
 '(helm-ff-file ((((type graphic)))))
 '(helm-ff-executable ((((type graphic)) :foreground "#1c9e28")))
 '(helm-ff-directory ((((type graphic)) :inherit dired-directory)))
 '(helm-ff-symlink ((((type graphic)) :inherit dired-symlink)))
 '(helm-ff-invalid-symlink ((((type graphic)) :inherit dired-warning)))
 '(helm-ff-prefix ((((type graphic)) :background "#d9ceb2" :foreground "#d81212")))
 '(helm-buffer-directory ((((type graphic)) :inherit helm-ff-directory)))
 '(helm-buffer-saved-out ((((type graphic)) :background "#f6f0e1" :foreground "#f71010")))
 '(helm-buffer-not-saved ((((type graphic)) :foreground "#fa5151")))
 '(helm-buffer-process ((((type graphic)) :foreground "#008b45")))
 '(helm-buffer-size ((((type graphic)) :foreground "#358d8d")))
 '(helm-grep-file ((((type graphic)) :inherit compilation-info)))
 '(help-argument-name ((((type graphic)) :inherit font-lock-variable-name-face)))
 '(hl-line ((((type graphic)) :background "#d9ceb2")))
 '(hl-todo ((((type graphic)) :foreground "#f71010" :weight bold)))
 '(info-title-1 ((((type graphic)) :inherit alect-color-level-1 :height 1.5 :weight bold)))
 '(info-title-2 ((((type graphic)) :inherit alect-color-level-2 :height 1.4 :weight bold)))
 '(info-title-3 ((((type graphic)) :inherit alect-color-level-3 :height 1.3 :weight bold)))
 '(info-title-4 ((((type graphic)) :inherit alect-color-level-4 :height 1.2 :weight bold)))
 '(info-menu-header ((((type graphic)) :inherit alect-color-level-5 :height 1.1 :weight bold)))
 '(info-node ((((type graphic)) :foreground "#d81212")))
 '(info-menu-star ((((type graphic)) :foreground "#f71010")))
 '(Info-quoted ((((type graphic)) :foreground "#101010" :weight bold)))
 '(ido-first-match ((((type graphic)) :weight bold)))
 '(ido-only-match ((((type graphic)) :inherit ido-first-match :foreground "#0000ff")))
 '(ido-subdir ((((type graphic)) :inherit dired-directory)))
 '(ido-virtual ((((type graphic)) :foreground "#fa5151")))
 '(isearch-fail ((((type graphic)) :foreground "#262626" :background "#fa5151")))
 '(isearch ((((type graphic)) :foreground "#d3c7a0" :background "#101010")))
 '(lazy-highlight ((((type graphic)) :foreground "#f6f0e1" :background "#909090")))
 '(linum ((((type graphic)) :foreground "#6c6c6c")))
 '(magit-tag ((((type graphic)) :foreground "#9ca30b" :weight bold)))
 '(magit-log-author ((((type graphic)) :inherit alect-author)))
 '(magit-process-ok ((((type graphic)) :inherit magit-section-title :foreground "#028902")))
 '(magit-process-ng ((((type graphic)) :inherit magit-section-title :foreground "#f71010")))
 '(git-commit-summary ((((type graphic)) :weight bold)))
 '(git-commit-comment-branch ((((type graphic)) :foreground "#0000ff")))
 '(git-commit-comment-file ((((type graphic)) :inherit default)))
 '(git-commit-comment-heading ((((type graphic)) :inherit alect-title)))
 '(git-commit-comment-action ((((type graphic)) :foreground "#958323")))
 '(magit-branch ((((type graphic)) :foreground "#0505cc" :weight bold)))
 '(magit-log-sha1 ((((type graphic)) :foreground "#6a621b")))
 '(magit-log-head-label-head ((((type graphic)) :background "#f6f0e1" :foreground "#101010" :box (:line-width 2 :color "#f71010"))))
 '(magit-log-head-label-local ((((type graphic)) :inherit magit-log-head-label-default :foreground "#0000ff")))
 '(magit-log-head-label-remote ((((type graphic)) :inherit magit-log-head-label-default :foreground "#008b45")))
 '(magit-log-head-label-tags ((((type graphic)) :inherit magit-log-head-label-default :foreground "#9ca30b")))
 '(Man-overstrike ((((type graphic)) :foreground "#0d7b72" :weight bold)))
 '(markdown-header-face ((((type graphic)) :inherit alect-title-1)))
 '(markdown-header-face-1 ((((type graphic)) :inherit alect-title-1)))
 '(markdown-header-face-2 ((((type graphic)) :inherit alect-title-2)))
 '(markdown-header-face-3 ((((type graphic)) :inherit alect-title-3)))
 '(markdown-header-face-4 ((((type graphic)) :inherit alect-title-4)))
 '(markdown-header-face-5 ((((type graphic)) :inherit alect-title-5)))
 '(markdown-header-face-6 ((((type graphic)) :inherit alect-title-6)))
 '(markdown-header-rule-face ((((type graphic)) :inherit markdown-header-face :foreground "#3f3f3f")))
 '(markdown-header-delimiter-face ((((type graphic)) :inherit markdown-header-face :foreground "#101010")))
 '(markdown-bold-face ((((type graphic)) :inherit bold)))
 '(markdown-italic-face ((((type graphic)) :inherit italic)))
 '(markdown-link-face ((((type graphic)) :inherit link)))
 '(markdown-link-title-face ((((type graphic)) :inherit font-lock-string-face)))
 '(markdown-url-face ((((type graphic)) :foreground "#077707")))
 '(message-cited-text ((((type graphic)) :inherit font-lock-comment-face)))
 '(message-separator ((((type graphic)) :inherit font-lock-comment-face)))
 '(message-header-name ((((type graphic)) :foreground "#958323" :weight bold)))
 '(message-header-other ((((type graphic)) :foreground "#3f3f3f")))
 '(message-header-to ((((type graphic)) :foreground "#0000ff")))
 '(message-header-cc ((((type graphic)) :foreground "#2c53ca")))
 '(message-header-newsgroups ((((type graphic)) :foreground "#6a621b")))
 '(message-header-subject ((((type graphic)) :inherit alect-title)))
 '(message-header-xheader ((((type graphic)) :foreground "#1c9e28")))
 '(message-mml ((((type graphic)) :foreground "#0eaeae" :weight bold)))
 '(mode-line-buffer-id ((((type graphic)) :foreground "#2c53ca" :weight bold)))
 '(mode-line ((((type graphic)) :foreground "#262626" :background "#f6f0e1" :box (:line-width 2 :style released-button))))
 '(mode-line-inactive ((((type graphic)) :foreground "#6c6c6c" :background "#ded6c5" :box (:line-width 2 :color "#f6f0e1" :style nil))))
 '(mode-line-highlight ((((type graphic)) :inherit highlight :box (:line-width 1 :style released-button))))
 '(org-agenda-date ((((type graphic)) :inherit alect-time)))
 '(org-agenda-date-today ((((type graphic)) :inherit alect-selected-item :foreground "#0eaeae")))
 '(org-agenda-structure ((((type graphic)) :inherit alect-title)))
 '(org-archived ((((type graphic)) :foreground "#262626" :weight bold)))
 '(org-block ((((type graphic)) :background "#d9ceb2")))
 '(org-block-background ((((type graphic)) :background "#d9ceb2")))
 '(org-block-begin-line ((((type graphic)) :inherit org-meta-line :background "#d3c7a0")))
 '(org-block-end-line ((((type graphic)) :inherit org-block-begin-line)))
 '(org-checkbox ((((type graphic)) :background "#f6f0e1" :foreground "#3f3f3f" :box (:line-width 1 :style pressed-button))))
 '(org-date ((((type graphic)) :inherit alect-time)))
 '(org-date-selected ((((type graphic)) :inherit alect-selected-item)))
 '(org-done ((((type graphic)) :foreground "#259ea2" :weight bold)))
 '(org-document-title ((((type graphic)) :inherit alect-title)))
 '(org-document-info ((((type graphic)) :foreground "#e43838")))
 '(org-document-info-keyword ((((type graphic)) :foreground "#958323")))
 '(org-formula ((((type graphic)) :foreground "#ab9c3a")))
 '(org-headline-done ((((type graphic)) :foreground "#259ea2")))
 '(org-hide ((((type graphic)) :foreground "#f6f0e1")))
 '(org-level-1 ((((type graphic)) :inherit alect-title-1)))
 '(org-level-2 ((((type graphic)) :inherit alect-title-2)))
 '(org-level-3 ((((type graphic)) :inherit alect-title-3)))
 '(org-level-4 ((((type graphic)) :inherit alect-title-4)))
 '(org-level-5 ((((type graphic)) :inherit alect-title-5)))
 '(org-level-6 ((((type graphic)) :inherit alect-title-6)))
 '(org-level-7 ((((type graphic)) :inherit alect-title-7)))
 '(org-level-8 ((((type graphic)) :inherit alect-title-8)))
 '(org-link ((((type graphic)) :inherit link)))
 '(org-scheduled ((((type graphic)) :foreground "#3cb368")))
 '(org-scheduled-previously ((((type graphic)) :foreground "#fa5151")))
 '(org-scheduled-today ((((type graphic)) :foreground "#0505cc")))
 '(org-special-keyword ((((type graphic)) :inherit font-lock-doc-face)))
 '(org-table ((((type graphic)) :foreground "#505050")))
 '(org-tag ((((type graphic)) :slant italic)))
 '(org-time-grid ((((type graphic)) :foreground "#6c6c6c")))
 '(org-todo ((((type graphic)) :foreground "#f71010" :weight bold)))
 '(org-upcoming-deadline ((((type graphic)) :inherit font-lock-keyword-face)))
 '(org-verbatim ((((type graphic)) :foreground "#6c6c6c")))
 '(org-warning ((((type graphic)) :foreground "#f71010" :weight bold :underline nil)))
 '(org-column ((((type graphic)) :background "#f6f0e1")))
 '(org-column-title ((((type graphic)) :background "#f6f0e1" :underline t :weight bold)))
 '(outline-1 ((((type graphic)) :inherit alect-title-1)))
 '(outline-2 ((((type graphic)) :inherit alect-title-2)))
 '(outline-3 ((((type graphic)) :inherit alect-title-3)))
 '(outline-4 ((((type graphic)) :inherit alect-title-4)))
 '(outline-5 ((((type graphic)) :inherit alect-title-5)))
 '(outline-6 ((((type graphic)) :inherit alect-title-6)))
 '(outline-7 ((((type graphic)) :inherit alect-title-7)))
 '(outline-8 ((((type graphic)) :inherit alect-title-8)))
 '(popup-tip-face ((((type graphic)) :foreground "#070707" :background "#ab9c3a")))
 '(popup-scroll-bar-foreground-face ((((type graphic)) :background "#6c6c6c")))
 '(popup-scroll-bar-background-face ((((type graphic)) :background "#f6f0e1")))
 '(popup-isearch-match ((((type graphic)) :foreground "#262626" :background "#ded6c5")))
 '(rainbow-delimiters-depth-1-face ((((type graphic)) :foreground "#262626")))
 '(rainbow-delimiters-depth-2-face ((((type graphic)) :foreground "#077707")))
 '(rainbow-delimiters-depth-3-face ((((type graphic)) :foreground "#ab9c3a")))
 '(rainbow-delimiters-depth-4-face ((((type graphic)) :foreground "#358d8d")))
 '(rainbow-delimiters-depth-5-face ((((type graphic)) :foreground "#1c9e28")))
 '(rainbow-delimiters-depth-6-face ((((type graphic)) :foreground "#0505cc")))
 '(rainbow-delimiters-depth-7-face ((((type graphic)) :foreground "#9ca30b")))
 '(rainbow-delimiters-depth-8-face ((((type graphic)) :foreground "#008b45")))
 '(rainbow-delimiters-depth-9-face ((((type graphic)) :foreground "#0eaeae")))
 '(rcirc-my-nick ((((type graphic)) :foreground "#0000ff")))
 '(rcirc-other-nick ((((type graphic)) :foreground "#6c6c6c")))
 '(rcirc-bright-nick ((((type graphic)) :foreground "#0505cc")))
 '(rcirc-dim-nick ((((type graphic)) :foreground "#0eaeae")))
 '(rcirc-server ((((type graphic)) :foreground "#028902")))
 '(rcirc-server-prefix ((((type graphic)) :foreground "#008b45")))
 '(rcirc-timestamp ((((type graphic)) :inherit alect-time)))
 '(rcirc-nick-in-message ((((type graphic)) :foreground "#ef8300")))
 '(rcirc-nick-in-message-full-line ((((type graphic)) :weight bold)))
 '(rcirc-prompt ((((type graphic)) :inherit alect-prompt)))
 '(rcirc-track-nick ((((type graphic)) :inverse-video t)))
 '(rcirc-track-keyword ((((type graphic)) :weight bold)))
 '(rcirc-url ((((type graphic)) :weight bold)))
 '(rcirc-keyword ((((type graphic)) :foreground "#ef8300" :weight bold)))
 '(rst-level-1 ((((type graphic)) :inherit alect-title-1)))
 '(rst-level-2 ((((type graphic)) :inherit alect-title-2)))
 '(rst-level-3 ((((type graphic)) :inherit alect-title-3)))
 '(rst-level-4 ((((type graphic)) :inherit alect-title-4)))
 '(rst-level-5 ((((type graphic)) :inherit alect-title-5)))
 '(rst-level-6 ((((type graphic)) :inherit alect-title-6)))
 '(rst-reference ((((type graphic)) :inherit link)))
 '(rst-adornment ((((type graphic)) :foreground "#101010")))
 '(rst-literal ((((type graphic)) :foreground "#0d7b72")))
 '(ruler-mode-default ((((type graphic)) :inherit alect-tab-unselected :height 1.0)))
 '(ruler-mode-pad ((((type graphic)) :inherit ruler-mode-default)))
 '(ruler-mode-column-number ((((type graphic)) :inherit ruler-mode-default :foreground "#262626")))
 '(ruler-mode-current-column ((((type graphic)) :inherit ruler-mode-default :background "#1074cd" :foreground "#1074cd")))
 '(ruler-mode-comment-column ((((type graphic)) :inherit (font-lock-comment-face ruler-mode-default))))
 '(ruler-mode-fill-column ((((type graphic)) :inherit ruler-mode-default :foreground "#f71010" :weight bold)))
 '(ruler-mode-goal-column ((((type graphic)) :inherit ruler-mode-default :foreground "#e43838")))
 '(ruler-mode-tab-stop ((((type graphic)) :inherit ruler-mode-default :foreground "#0092ff")))
 '(ruler-mode-fringes ((((type graphic)) :inherit ruler-mode-default :foreground "#028902")))
 '(ruler-mode-margins ((((type graphic)) :inherit ruler-mode-default :foreground "#a020f0")))
 '(show-paren-mismatch ((((type graphic)) :foreground "#fafafa" :background "#f71010")))
 '(show-paren-match ((((type graphic)) :foreground "#fafafa" :background "#008b45")))
 '(slime-error-face ((((type graphic)) :inherit error)))
 '(slime-repl-output-mouseover-face ((((type graphic)) :inherit highlight)))
 '(term-color-black ((((type graphic)) :foreground "#070707" :background "#070707")))
 '(term-color-white ((((type graphic)) :foreground "#fafafa" :background "#fafafa")))
 '(term-color-red ((((type graphic)) :foreground "#d81212" :background "#f71010")))
 '(term-color-green ((((type graphic)) :foreground "#008b45" :background "#028902")))
 '(term-color-yellow ((((type graphic)) :foreground "#9ca30b" :background "#958323")))
 '(term-color-blue ((((type graphic)) :foreground "#0000ff" :background "#2c53ca")))
 '(term-color-magenta ((((type graphic)) :foreground "#9400d3" :background "#a020f0")))
 '(term-color-cyan ((((type graphic)) :foreground "#358d8d" :background "#0d7b72")))
 '(vc-up-to-date-state ((((type graphic)) :foreground "#1c9e28")))
 '(vc-edited-state ((((type graphic)) :foreground "#958323")))
 '(vc-missing-state ((((type graphic)) :foreground "#f71010")))
 '(vc-conflict-state ((((type graphic)) :foreground "#b22222" :weight bold)))
 '(vc-locked-state ((((type graphic)) :foreground "#259ea2")))
 '(vc-locally-added-state ((((type graphic)) :foreground "#0000ff")))
 '(vc-needs-update-state ((((type graphic)) :foreground "#a020f0")))
 '(vc-removed-state ((((type graphic)) :foreground "#e43838")))
 '(whitespace-space ((((type graphic)) :foreground "#d3c7a0")))
 '(whitespace-hspace ((((type graphic)) :background "#d9ceb2" :foreground "#ef8300")))
 '(whitespace-tab ((((type graphic)) :background "#d3c7a0" :foreground "#0092ff")))
 '(whitespace-newline ((((type graphic)) :foreground "#0092ff")))
 '(whitespace-trailing ((((type graphic)) :inherit trailing-whitespace)))
 '(whitespace-line ((((type graphic)) :background "#f6f0e1")))
 '(whitespace-empty ((((type graphic)) :background "#d3c7a0")))
 '(whitespace-indentation ((((type graphic)) :background "#d3c7a0" :foreground "#f71010")))
 '(whitespace-space-before-tab ((((type graphic)) :background "#d3c7a0" :foreground "#028902")))
 '(whitespace-space-after-tab ((((type graphic)) :background "#d3c7a0" :foreground "#0000ff")))
 '(widget-field ((((type graphic)) :background "#d9ceb2" :box (:line-width -1 :color "#6c6c6c" :style nil))))
 '(widget-button ((((type graphic)) :inherit alect-button)))
 '(widget-button-pressed ((((type graphic)) :inherit alect-button-pressed)))
 '(widget-documentation ((((type graphic)) :foreground "#1c9e28")))
 '(widget-inactive ((((type graphic)) :inherit shadow)))
 '(widget-single-line-field ((((type graphic)) :foreground "#3f3f3f" :inherit widget-field)))
 '(default ((((type graphic)) :foreground "#262626" :background "#ded6c5"))))

(provide-theme 'alect-light)
