(deftheme flatui
  "Created 2015-08-26.")

(custom-theme-set-variables
 'flatui
 '(ansi-color-names-vector ["#ecf0f1" "#e74c3c" "#2ecc71" "#f1c40f" "#2492db" "#9b59b6" "#1abc9c" "#2c3e50"]))

(custom-theme-set-faces
 'flatui
 '(button ((t (:underline t))))
 '(link ((t (:foreground "#2492db" :underline t :weight bold))))
 '(link-visited ((t (:foreground "#9b59b6" :underline t :weight normal))))
 '(cursor ((t (:foreground "#2c3e50" :background "#34495e"))))
 '(escape-glyph ((t (:foreground "#f1c40f" :bold t))))
 '(fringe ((t (:foreground "#34495e" :background "#dfe4ea"))))
 '(header-line ((t (:foreground "#16a085" :background "#34495e" :box (:line-width -1 :style released-button)))))
 '(highlight ((t (:background "#dfe4ea"))))
 '(success ((t (:foreground "#27ae60" :weight bold))))
 '(warning ((t (:foreground "#d35400" :weight bold))))
 '(compilation-info ((t (:foreground "#27ae60" :underline t))))
 '(compilation-line-number ((t (:foreground "#f1c40f"))))
 '(compilation-mode-line-exit ((t (:foreground "#1abc9c" :weight bold))))
 '(compilation-mode-line-fail ((t (:foreground "#c0392b" :weight bold))))
 '(compilation-mode-line-run ((t (:foreground "#d98c10" :weight bold))))
 '(match ((t (:background "#1abc9c" :foreground "#34495e"))))
 '(isearch ((t (:foreground "#ecf0f1" :weight bold :background "#e74c3c"))))
 '(isearch-fail ((t (:foreground "#f1c40f" :weight bold :background "#c0392b"))))
 '(lazy-highlight ((t (:foreground "#34495e" :weight bold :background "#f1c40f"))))
 '(menu ((t (:foreground "#2c3e50" :background "#dfe4ea"))))
 '(minibuffer-prompt ((t (:foreground "#34495e" :weight bold))))
 '(region ((((class color) (min-colors 89)) (:background "#f1c40f" :foreground "#2c3e50")) (t :inverse-video t)))
 '(secondary-selection ((t (:background "#1abc9c"))))
 '(trailing-whitespace ((t (:background "#e74c3c"))))
 '(vertical-border ((t (:foreground "#dfe4ea"))))
 '(font-lock-builtin-face ((t (:foreground "#16a085"))))
 '(font-lock-comment-face ((t (:foreground "#7f8c8d"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#95a5a6"))))
 '(font-lock-constant-face ((t (:foreground "#e67e22"))))
 '(font-lock-doc-face ((t (:foreground "#7f8c8d"))))
 '(font-lock-function-name-face ((t (:foreground "#34495e" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "#d98c10"))))
 '(font-lock-negation-char-face ((t (:foreground "#2492db" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#e74c3c" :weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#d98c10" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#9b59b6" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#0a74b9"))))
 '(font-lock-type-face ((t (:foreground "#2492db"))))
 '(font-lock-variable-name-face ((t (:foreground "#8e44ad"))))
 '(font-lock-warning-face ((t (:foreground "#d35400" :weight bold))))
 '(c-annotation-face ((t (:inherit font-lock-constant-face))))
 '(ac-candidate-face ((t (:background "#95a5a6" :foreground "#2c3e50"))))
 '(ac-selection-face ((t (:background "#7f8c8d" :foreground "#2c3e50"))))
 '(popup-tip-face ((t (:background "#f1c40f" :foreground "#2c3e50"))))
 '(popup-scroll-bar-foreground-face ((t (:background "#7f8c8d"))))
 '(popup-scroll-bar-background-face ((t (:background "#dfe4ea"))))
 '(popup-isearch-match ((t (:background "#ecf0f1" :foreground "#2c3e50"))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "#27ae60" :background "#ecf0f1")) (t (:foreground "#27ae60" :background "#ecf0f1"))))
 '(diff-changed ((t (:foreground "#e67e22"))))
 '(diff-context ((t (:foreground "#95a5a6"))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "#e74c3c" :background "#ecf0f1")) (t (:foreground "#e74c3c" :background "#ecf0f1"))))
 '(diff-refine-added ((t :inherit diff-added :background "#2ecc71" :weight bold)))
 '(diff-refine-changed ((t :inherit diff-changed :weight bold)))
 '(diff-refine-removed ((t :inherit diff-removed :background "#c0392b" :weight bold)))
 '(diff-header ((((class color) (min-colors 89)) (:foreground "#2c3e50" :weight bold)) (t (:foreground "#2c3e50" :weight bold))))
 '(diff-file-header ((((class color) (min-colors 89)) (:foreground "#2c3e50" :weight bold)) (t (:foreground "#2c3e50" :weight bold))))
 '(diff-hunk-header ((((class color) (min-colors 89)) (:foreground "#8e44ad" :weight bold)) (t (:foreground "#8e44ad" :weight bold))))
 '(ediff-current-diff-A ((t (:foreground "#2c3e50" :background "#e74c3c"))))
 '(ediff-current-diff-Ancestor ((t (:foreground "#2c3e50" :background "#e74c3c"))))
 '(ediff-current-diff-B ((t (:foreground "#2c3e50" :background "#2ecc71"))))
 '(ediff-current-diff-C ((t (:foreground "#2c3e50" :background "#2492db"))))
 '(ediff-even-diff-A ((t (:background "#ecf0f1"))))
 '(ediff-even-diff-Ancestor ((t (:background "#ecf0f1"))))
 '(ediff-even-diff-B ((t (:background "#dfe4ea"))))
 '(ediff-even-diff-C ((t (:background "#dfe4ea"))))
 '(ediff-fine-diff-A ((t (:foreground "#2c3e50" :background "#e74c3c" :weight bold))))
 '(ediff-fine-diff-Ancestor ((t (:foreground "#2c3e50" :background "#e74c3c" weight bold))))
 '(ediff-fine-diff-B ((t (:foreground "#2c3e50" :background "#2ecc71" :weight bold))))
 '(ediff-fine-diff-C ((t (:foreground "#2c3e50" :background "#2492db" :weight bold))))
 '(ediff-odd-diff-A ((t (:background "#dfe4ea"))))
 '(ediff-odd-diff-Ancestor ((t (:background "#dfe4ea"))))
 '(ediff-odd-diff-B ((t (:background "#dfe4ea"))))
 '(ediff-odd-diff-C ((t (:background "#dfe4ea"))))
 '(flycheck-error ((((supports :underline (:style wave))) (:underline (:style wave :color "#e74c3c") :inherit unspecified)) (t (:foreground "#e74c3c" :weight bold :underline t))))
 '(flycheck-warning ((((supports :underline (:style wave))) (:underline (:style wave :color "#d98c10") :inherit unspecified)) (t (:foreground "#f1c40f" :weight bold :underline t))))
 '(flycheck-info ((((supports :underline (:style wave))) (:underline (:style wave :color "#8e44ad") :inherit unspecified)) (t (:foreground "#9b59b6" :weight bold :underline t))))
 '(flycheck-fringe-error ((t (:foreground "#c0392b" :weight bold))))
 '(flycheck-fringe-warning ((t (:foreground "#d98c10" :weight bold))))
 '(flycheck-fringe-info ((t (:foreground "#8e44ad" :weight bold))))
 '(flymake-errline ((((supports :underline (:style wave))) (:underline (:style wave :color "#e74c3c") :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground "#e74c3c" :weight bold :underline t))))
 '(flymake-warnline ((((supports :underline (:style wave))) (:underline (:style wave :color "#d98c10") :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground "#d98c10" :weight bold :underline t))))
 '(flyspell-duplicate ((((supports :underline (:style wave))) (:underline (:style wave :color "#d98c10") :inherit unspecified)) (t (:foreground "#d98c10" :weight bold :underline t))))
 '(flyspell-incorrect ((((supports :underline (:style wave))) (:underline (:style wave :color "#e74c3c") :inherit unspecified)) (t (:foreground "#e74c3c" :weight bold :underline t))))
 '(git-gutter:added ((t (:foreground "#2ecc71" :weight bold))))
 '(git-gutter:deleted ((t (:foreground "#e74c3c" :weight bold))))
 '(git-gutter:modified ((t (:foreground "#e67e22" :weight bold))))
 '(git-gutter:unchanged ((t (:foreground "#2c3e50" :weight bold))))
 '(helm-action ((t (:underline nil))))
 '(helm-selection ((t (:background "#f1c40f" :underline nil :weight bold))))
 '(helm-candidate-number ((t (:foreground "#1abc9c"))))
 '(helm-source-header ((t (:foreground "#2c3e50" :weight bold))))
 '(helm-visible-mark ((t (:foreground "#e74c3c"))))
 '(helm-ff-directory ((t (:foreground "#2492db"))))
 '(helm-ff-executable ((t (:foreground "#d35400"))))
 '(helm-ff-symlink ((t (:foreground "#ecf0f1" :background "#9b59b6"))))
 '(helm-ff-prefix ((t (:foreground "#e74c3c"))))
 '(helm-M-x-key ((t (:foreground "#7f8c8d"))))
 '(helm-grep-file ((t (:foreground "#1abc9c"))))
 '(helm-grep-lineno ((t (:foreground "#7f8c8d"))))
 '(helm-grep-running ((t (:foreground "#e74c3c"))))
 '(helm-grep-finish ((t (:foreground "#1abc9c"))))
 '(helm-buffer-saved-out ((t (:foreground "#d98c10" :background nil))))
 '(helm-moccur-buffer ((t (:foreground "#7f8c8d"))))
 '(hl-line ((((class color) (min-colors 89)) (:background "#dfe4ea")) (t :weight bold)))
 '(ido-first-match ((t (:foreground "#d35400" :weight bold))))
 '(ido-only-match ((t (:foreground "#e67e22" :weight bold))))
 '(ido-subdir ((t (:foreground "#d98c10"))))
 '(ido-indicator ((t (:foreground "#f1c40f" :background "#d35400"))))
 '(linum ((t (:foreground "#34495e" :background "#dfe4ea"))))
 '(outline-1 ((t (:foreground "#16a085"))))
 '(outline-2 ((t (:foreground "#0a74b9"))))
 '(outline-3 ((t (:foreground "#8e44ad"))))
 '(outline-4 ((t (:foreground "#d98c10"))))
 '(outline-5 ((t (:foreground "#d35400"))))
 '(outline-6 ((t (:foreground "#c0392b"))))
 '(show-paren-mismatch ((t (:foreground "#f1c40f" :background "#c0392b" :weight bold))))
 '(show-paren-match ((t (:foreground "#ecf0f1" :background "#e74c3c" :weight bold))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#ecf0f1" :background "#2c3e50" :box (:line-width -1 :style released-button))) (t :inverse-video t)))
 '(mode-line-inactive ((t (:foreground "#34495e" :background "#dfe4ea" :box (:line-width -1 :style released-button)))))
 '(mode-line-buffer-id ((t (:foreground "#e74c3c" :weight bold))))
 '(whitespace-space ((t (:background "#ecf0f1" :foreground "#f1c40f"))))
 '(whitespace-hspace ((t (:background "#ecf0f1" :foreground "#f1c40f"))))
 '(whitespace-tab ((t (:background "#e67e22"))))
 '(whitespace-newline ((t (:foreground "#f1c40f"))))
 '(whitespace-trailing ((t (:background "#e74c3c"))))
 '(whitespace-line ((t (:background nil :foreground "#e74c3c"))))
 '(whitespace-space-before-tab ((t (:background "#ecf0f1" :foreground "#e74c3c"))))
 '(whitespace-indentation ((t (:background "#ecf0f1" :foreground "#f1c40f"))))
 '(whitespace-empty ((t (:background "#d98c10"))))
 '(whitespace-space-after-tab ((t (:background "#ecf0f1" :foreground "#e74c3c"))))
 '(default ((t (:foreground "#2c3e50" :background "#ecf0f1")))))

(provide-theme 'flatui)
